### ISSUE TITLE
[Enhancement] Allow certain fields as optional for `gravity resource create`

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1016]
**What Happened**

When the SMTP server replies with an empty AUTH option 250-AUTH Kapacitor it just sends the QUIT command without attempting delivery. The server is sending this empty as authentication is not required, but the gravity command line tool does not allow to leave username and password values empty:

`$ sudo gravity resource create -f alert-smtp.yaml`
`[ERROR]: failed to validate: username: username is required,password: password is required`

**Expected Behavior**

Configuration tool should accept these values as optional instead of enforcing them. Manually touching Kubernetes config maps addressed this issue but is not scalable.

**Environment**

Gravity (5.5.x)

**Comment by r0mant** [comment]
This was done.
