### ISSUE TITLE
[BUG] Unnecessary error message by telegraf-node

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1027]
**Describe the bug**

The etcd cert has the one of the controller IP in the Alternative Name. 172.19.0.122 in this case.

```
X509v3 Subject Alternative Name:
DNS:ip-172-19-0-122.ap-southeast-2.compute.internal, IP Address:127.0.0.1, IP Address:127.0.0.2, IP Address:172.19.0.122
```
In the telegraf-node pod, repetitive error messages are seen every 20s

`2019-04-27T02:10:20Z E! Error in plugin [inputs.prometheus]: error making HTTP request to https://172.19.0.114:2379/metrics: Get https://172.19.0.114:2379/metrics: x509: certificate is valid for 127.0.0.1, 127.0.0.2, 172.19.0.122, not 172.19.0.114`

172.19.0.114 is one of the workers. This error is seen on every node except the 172.19.0.122. The error was be avoided by replacing `172.19.0.114` with `127.0.0.1` in the request. 

**Expected behavior**

If error can be ignored then we should address as such the user is not seeing a repetitive error message every 20s. 

Although addressed in Gravity 6.X given we removed influxdb/telegraf, flagging this as backport for 5.5 as this has been hurting adoption and perception of product quality. 

**Environment (please complete the following information):**
 - Gravity: 5.5.X

**Comment by UnderGreen** [comment]
Fixed in https://github.com/gravitational/monitoring-app/releases/tag/5.5.5.
Released with gravity [5.5.29](https://github.com/gravitational/gravity/releases/tag/5.5.29).
