### ISSUE TITLE
Remove `opscenter` target from OSS Makefile

### ISSUE THREAD

**Issue by eldios** [gravitational/gravity#103]
We should remove the `opscenter` (and related) target from OSS Makefile since that's not functional anymore since when we moved this part only in the Enterprise edition.

**Comment by kontsevoy** [comment]
@eldios the OSS edition Gravity does have some useless targets on purpose, they simplify enterprise builds so we don't have to update existing automation in the process of open sourcing.

**Comment by kontsevoy** [comment]
if I answered your question, do you mind closing this pls? thx

**Comment by eldios** [comment]
Had chat about this with @kontsevoy and decided that we should probably move the extra targets into a `internal.mk` file which we can include at the bottom of `Makefile` with a comment saying "for internal use only" or similar explanatory comment.
