### ISSUE TITLE
[BUG] cluster stuck in expanding without any recovery attempt 

### ISSUE THREAD

**Issue by helgi** [gravitational/gravity#1036]
Cluster stays in `expand` forever

```
Active operations:
    * operation_expand (b9a24077-6c26-416e-9bca-1e2cce7850c3)
      started:	Thu Jan  9 08:03 UTC (1 week ago)
      Wait for the planet to start, 70% complete
```

Can't complete or remove it, needs `etcd` surgery probably? No clue what node this is related to. Staying in any given operational state for a long time, without finishing, should be handled somehow. GC or notification somehow, or at least unblock other operations that are waiting on `active` state

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: CentOS 7.6
 - Gravity [e.g. 5.5.4]: 5.4.10 (old, yes, can't recall seeing this on newer but wouldn't exclude it)
 - Platform [e.g. Vmware, AWS]: AWS

**Comment by helgi** [comment]
Have another cluster, also 5.4.10, in this state:

```
Active operations:
    * operation_expand (ed493edb-76d3-41ae-8b21-e3c43996cccd)
      started:	Mon Jan 13 23:03 UTC (1 week ago)
      Wait for the planet to start, 70% complete
```

Note that these are *worker* nodes and not *masters*

**Comment by anandkumarpatel** [comment]
Shrink ooperations can also hang.
```
Cluster name:           stable4
Cluster status:         shrinking
Application:            core-paas, version 0.0.15
Periodic updates:       OFF
Remote support:
    opscenter: ON
Active operations:
    * operation_shrink (31595672-cbca-4054-b48d-cb4ad91b435d)
      started:  Tue Feb 11 21:24 UTC (27 minutes ago)
      initializing the operation, 0% complete
```
```
gravity version
Edition:        enterprise
Version:        6.2.5
Git Commit:     5794ad618bd19b32652bfc1223b16b2d27498466
Helm Version:   v2.12
```
