### ISSUE TITLE
Implement more pre-upgrade checks

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1068]
A lot of times the upgrade fails due to some networking misconfigurations on the customer infrastructure. Gravity should detect these issues and refuse to proceed with the upgrade.

This is a pretty vague problem statement, we should populate this ticket with more specific ideas of what exactly to check for and add respective Satellite checks.

**Comment by r0mant** [comment]
Too vague, going to close this.

**Comment by wadells** [comment]
https://github.com/gravitational/gravity/issues/1735 is a concrete check we should implement.
