### ISSUE TITLE
[5.5.x] improve clean up logic for failed expand operations

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1077]
Improve logic for when the expand operation fails or when the agent is explicitly terminated.
Also, provide a set of sub-commands to deal with orphaned operations in a safe manner.

**Comment by helgi** [comment]
Seems like this will solve part of https://github.com/gravitational/gravity/issues/900 for me :) and perhaps part of https://github.com/gravitational/gravity/issues/897 as well

**Comment by aelkugia** [comment]
I had created #1127 but will close as redundant. A customer ran into this issue -

**What happened:**

For expands, the presence of pending previous expand operations can be a blocker. In order to be able to start a new expand operation, the pending ones need to be removed from the queue (in etcd). Currently, we have been providing customers at times with a script to do so.

**What should happen:**

There should be a dedicated troubleshooting command to remove errored operations. A potential auto-fix/auto-detect and recover from state would lead to an even more improved user experience.

**Example script used:**

```
#!/bin/bash
set -Eeou pipefail
function die {
  >&2 echo $@
  exit 1
}
if [ "$EUID" -ne 0 ]
  then echo "Please run the script as root"
  exit
fi
status=$(gravity status --output=json)
cluster_name=$(echo "${status}" | jq -r ".cluster.domain")
operation_ids=$(echo "${status}" | jq -c -r '.cluster.active_operations[]? | select(.type=="operation_expand") | .id')
if [ "" = "${operation_ids}" ]; then
  die "No active expand operation found"
fi
for id in ${operation_ids}; do
  gravity enter -- --notty /usr/bin/etcdctl -- rm --recursive /gravity/local/sites/${cluster_name}/ops/${id}
done
gravity status-reset
```

**Comment by a-palchikov** [comment]
* extended debug logging (incl. gRPC logs)
 * add expiration to controller reconnect loop
 * attempt to properly fail operation in case of abort (add context HTTP APIs if possible)
 * (tentative) streaming logs from agent
 * automatically fail pending operations that do not make progress
 * complicate logic of operation state transitioning (if join a worker node, cluster can transition to active on error) - same for shrink.

**Comment by helgi** [comment]
Will this address https://github.com/gravitational/gravity/issues/1036 ?

**Comment by a-palchikov** [comment]
Partially yes - once the changes are forward-ported to 6.2.x.

**Comment by helgi** [comment]
Has this been forward ported?

**Comment by a-palchikov** [comment]
@helgi Yes, the short answer is that it has been. The longer is - the 6.x upwards have diverted from 5.x w.r.t agent handling but the 6.3.x branch has been updated to set the operation to failed upon any error on the side of the joining node to the same effect as 5.x.
There's a small improvement that I need to backport from [here](https://github.com/gravitational/gravity/pull/1542) - working on it.

**Comment by helgi** [comment]
Thanks! What about for 7.x?

**Comment by a-palchikov** [comment]
We're keeping 7.x in sync in any way - so it gets all the same patches.
