### ISSUE TITLE
Flannel routes sometimes missing

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1090]
Sometimes routes for some nodes that flannel is supposed to create for nodes are missing. Need to figure out why that happens and how to fix.

**Comment by r0mant** [comment]
At a minimum we should add a check to satellite to check for missing routes. And maybe automatically restart flannel in this case.

**Comment by aelkugia** [comment]
Closed per: #1071 (addressing issue with flannel incorrectly recovering from a watch failure ) and [#617 ](https://github.com/gravitational/planet/pull/617)(Upgrade etcd to 3.3.20 in order to fix a problem with missed etcd events)
