### ISSUE TITLE
Planet agent gets stuck

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1091]
Planet agents may get stuck and thus will not be able to start apiserver and other control plane components.

Version: 5.2.x

Exact version and planet agent logs are TBD.

**Comment by a-palchikov** [comment]
Going forward, I'd implement another endpoint to capture the state of the process behind mTLS to be able to tell where it's stuck as it'd be impossible or pretty hard to nail down.

**Comment by r0mant** [comment]
The only logs from the planet agent we could collect: [planet-agent-logs.txt](https://github.com/gravitational/gravity/files/4233506/planet-agent-logs.txt).

The planet version was `5.2.23-11109`.

**Comment by knisbet** [comment]
@r0mant I'm not sure if you're aware of this or not, but golang will print stack traces and exit when killed with the ABRT signal. https://pro-tips-dot-com.tumblr.com/post/47677612115/kill-a-hung-go-process-and-print-stack-traces

**Comment by r0mant** [comment]
Oh yes, I completely forgot about it. Thanks for reminding, it might come handy during troubleshooting.

**Comment by r0mant** [comment]
https://github.com/gravitational/gravity/issues/2007 duplicate.
