### ISSUE TITLE
Gravity status should report status of system pods

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1092]
If any of the system pods are crashing (gravity-site, dns), gravity status will not report that and say cluster is healthy.

**Comment by knisbet** [comment]
I believe on 6.x+ the prometheus/alert manager monitoring will report situations like this.

**Comment by r0mant** [comment]
Yeah, but it won't make the cluster degraded IIRC and hence won't prevent operations from launching. Probably doesn't make sense to degrade the cluster if _any_ pod is crashing, but I think that for system-level pods such as gravity-site, coredns, etc. we need a tighter integration with satellite so if any of them are down a customer can't launch upgrade.

**Comment by helgi** [comment]
Given the monitoring stack can be made optional then ideally this functionality works without prom/alert. I've had to check for the daemonset and the pods to augment `gravity status` in certain use-cases FWIW

**Comment by r0mant** [comment]
Will be a part of next 5.5 release, forward-ports are tracked in https://github.com/gravitational/gravity/issues/1740.
