### ISSUE TITLE
Consider removing or loosening the same OS requirement

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1112]
This has been brought up multiple times and gets in the way without clear benefits.

If there're benefits - we should document them clearly.
If there aren't any - we should drop the requirement given that:
  * manifest lists all available OS distribution requirements for a node
  * OS distribution is one of the [officially supported](https://gravitational.com/gravity/docs/requirements/#linux-distributions)

There maybe legitimate requirements to build the environment based on type of the workload which might include a specialized distribution or version.

**Comment by r0mant** [comment]
https://github.com/gravitational/gravity/issues/1913 duplicate.
