### ISSUE TITLE
[BUG] Login screen is shown before completing installation steps

### ISSUE THREAD

**Issue by UnderGreen** [gravitational/gravity#1113]
**Describe the bug**
<img width="506" alt="Screen Shot 2020-02-17 at 8 34 13 AM" src="https://user-images.githubusercontent.com/2656737/74678116-0d5fb680-5188-11ea-9be6-6d8a6e9e0a6b.png">
This login screen is shown while installing gravity 5.5.x cluster. Before completing bandwagon steps there are no users to login with, what confuses our customers.

**To Reproduce**

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 5.5.x
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by alex-kovoy** [comment]
> Before completing bandwagon steps there are no users to login with, what confuses our customers.

Is it a custom bandwagon step?

**Comment by alex-kovoy** [comment]
@UnderGreen can it be closed?

**Comment by alex-kovoy** [comment]
[Some updates]
It appears that this has been fixed in `5.5.37`. This is about wizard generating an invalid token.

**Comment by UnderGreen** [comment]
@alex-kovoy I am awaiting response from the customer who reported that issue. When they prove that everything is fine with 5.5.37 I will close the issue.
