### ISSUE TITLE
[6.X] [master] forward port #637 intermediate upgrades

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#1115]
While I was reading the intermediate upgrade docs here:

https://github.com/gravitational/gravity/blob/0c98837246b6c4847b6a7c6cace40066dbbf06b2/docs/6.x/cluster.md#direct-upgrades-from-older-lts-versions

I became confused because `tele build --upgrade-via` flag was not available in the latest `tele` or any `tele` from 6.X.

After discussing with @a-palchikov and @r0mant, it looks like the plan is to port the --upgrade-via work done in #637 to 6.x and master, but it hasn't been a priority yet.  This issue exists to track that forward port work.

**Comment by wadells** [comment]
Please re-open https://github.com/gravitational/robotest/issues/156 when this forward porting is complete, to make sure that we're adequately testing it in all supported branches.

**Comment by a-palchikov** [comment]
We are testing the intermediate upgrades in relevant branches (5.5.x and 7.0.x currently).
