### ISSUE TITLE
[Enhancement] Add dedicated troubleshooting command to remove errored operations

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1127]
**What happened:**

For expands, the presence of pending previous expand operations can be a blocker. In order to be able to start a new expand operation, the pending ones need to be removed from the queue (in etcd). Currently, we have been providing customers at times with a script to do so.

**What should happen:**

There should be a dedicated troubleshooting command to remove errored operations. A potential auto-fix/auto-detect and recover from state would lead to an even more improved user experience. 

**Example script used:**

```
#!/bin/bash
set -Eeou pipefail
function die {
  >&2 echo $@
  exit 1
}
if [ "$EUID" -ne 0 ]
  then echo "Please run the script as root"
  exit
fi
status=$(gravity status --output=json)
cluster_name=$(echo "${status}" | jq -r ".cluster.domain")
operation_ids=$(echo "${status}" | jq -c -r '.cluster.active_operations[]? | select(.type=="operation_expand") | .id')
if [ "" = "${operation_ids}" ]; then
  die "No active expand operation found"
fi
for id in ${operation_ids}; do
  gravity enter -- --notty /usr/bin/etcdctl -- rm --recursive /gravity/local/sites/${cluster_name}/ops/${id}
done
gravity status-reset
```

**Comment by helgi** [comment]
Will help with https://github.com/gravitational/gravity/issues/900

**Comment by aelkugia** [comment]
Closing as this is redundant with #1077
