### ISSUE TITLE
[Test plan] Standalone cluster

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1134]
#### CLI mode

- [x] Install Telekube cluster image in standalone CLI mode.
  - [x] Verify can create [local user](https://gravitational.com/gravity/docs/ver/6.x/config/#example-provisioning-a-cluster-admin-user), for example:
```yaml
kind: user
version: v2
metadata:
  name: admin@example.com
spec:
  type: admin
  roles: ["@teleadmin"]
  password: qwe123
```
  - [x] Verify can invite user to cluster using CLI.
    - [x] Create a user invite: `gravity users add test@example.com --roles=@teleadmin`.
    - [x] Open the generated link and signup.
    - [x] Verify can login with the created user.
  - [x] Verify can reset cluster user password using CLI.
    - [x] Request a user reset: `gravity users reset test@example.com`.
    - [x] Open the generated link and reset the password.
    - [x] Verify can login with the new password.
  - [x] Verify can log into local cluster UI using the user created above.
  - [x] Verify can join a node using CLI (`gravity join`).
  - [x] Verify can remove a node using CLI (`gravity leave`).

#### UI mode

- [x] Install Telekube cluster image in standalone UI wizard mode.
  - [x] Verify can complete bandwagon through wizard UI.
  - [x] Verify can log into local cluster UI with the user created in bandwagon.

**Comment by wadells** [comment]
I'd like to help out with at least the "Cluster Upgrade & Join" portion of this, as it relates to my robotest work and I've yet to run an upgrade by hand.

**Comment by r0mant** [comment]
@wadells Sounds good - I collected some upgrade-related scenarios in https://github.com/gravitational/gravity/issues/1140.
