### ISSUE TITLE
[BUG] Console in Ops Center does not allow to enter lengthy commands 

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1145]
**Describe the bug**

Copying a command and attempting to paste in Ops Center leads to part of it being cut off if it is a lengthy command.

**To Reproduce**

Attempted to copy the following command:

```
sudo gravity planet enter -- --notty /usr/bin/gravity -- user create --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure --email=username@myorganization.com --password=myNewPassword --type=admin
```

In the console in Ops Center it shows:

```
sudo gravity planet enter -- --notty /usr/bin/gravity -- user create --ops-url=https://gravity-site.ku
be-system.svc.cluster.loca
```

**Expected behavior**

Seems like there is a copy/paste character limit. This is addressed in Gravity 6.X, but this ticket is a backport to 5.5.X. 

The expected behavior, is the full command that is copied (regardless of length) can be pasted in the console in Ops Center.

**Environment:**
 - Google Chrome: Version 78.0.3904.87 (Official Build) (64-bit)
 - Gravity: 5.5.28

**Comment by pablodcar** [comment]
It's happening in 5.5.37 too. Same problem in Firefox and Chrome.

**Comment by alex-kovoy** [comment]
It has been fixed in teleport (thanks to @paihu!!) a while back  https://github.com/gravitational/teleport/issues/2313 on the backend.

To fix it in Gravity, we need to packport the right teleport version to fix this.

**Comment by aelkugia** [comment]
The following PR ([#2325](https://github.com/gravitational/teleport/pull/2325)) added buffer to terminal to address this issue, as mentioned above will need to be backported
