### ISSUE TITLE
Add profiling/goroutine dump endpoint to satellite

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1146]
Otherwise it's very hard to debug what's happening to it.

**Comment by bernardjkim** [comment]
Profile endpoint added in gravitational/planet#224
To enable profiling endpoint, provide planet agent with `httpprofile` flag.

`httpprofile - enable profiling endpoint on specified host/port i.e. localhost:7070`

More info on golang diagnostics tools https://golang.org/doc/diagnostics.html

**Comment by klizhentas** [comment]
@bernardjkim can you folks try to make it consistent with our `--diag-addr` setting in teleport?

https://github.com/gravitational/teleport/blob/6b5935fb71f7de97626f1845de59d3daf4b9706a/tool/tctl/common/top_command.go#L58

https://github.com/gravitational/teleport/blob/6b5935fb71f7de97626f1845de59d3daf4b9706a/lib/service/service.go#L1512
