### ISSUE TITLE
[BUG] timeouts on imagepull of large container

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#1167]
Based on a customer call, no specific logs or errors, but the verbal indication is it takes a long time to pull and start large containers, probably due to timeouts within the pull process.

Might be worth increasing this parameter on kubelet:
```
--image-pull-progress-deadline duration
--
  | If no pulling progress is made before this deadline, the image pulling will be cancelled. This docker-specific flag only works when container-runtime is set to docker. (default 1m0s)
```

Reference: https://openai.com/blog/scaling-kubernetes-to-2500-nodes/ on pulling larger images.

**Comment by aelkugia** [comment]
Closed per [#596 ](https://github.com/gravitational/planet/pull/596)
