### ISSUE TITLE
[BUG] Node degraded due to kube-apiserver after upgrade

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1209]
**Describe the bug**

This was observed in robotest. The upgrade operation completes successfully but the status shows unhealthy due to kube-apiserver unit being in a failed state on one of the nodes:

`"nodes":[{"hostname":"robotest-660fd05b-node-1","advertise_ip":"10.142.15.236","role":"master","profile":"node","status":"healthy"},{"hostname":"robotest-660fd05b-node-2","advertise_ip":"10.142.15.238","role":"master","profile":"node","status":"degraded","failed_probes":["kube-apiserver.service (failed)"]},{"hostname":"robotest-660fd05b-node-0","advertise_ip":"10.142.15.237","role":"master","profile":"node","status":"healthy"}]`

Looking into the logs, apiserver shut down with an error on that node:

```
Mar 05 04:52:23 robotest-660fd05b-node-2 systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 05 04:52:23 robotest-660fd05b-node-2 systemd[1]: kube-apiserver.service: Failed with result 'exit-code'.
Mar 05 04:52:23 robotest-660fd05b-node-2 systemd[1]: Stopped Kubernetes API Server.
```

On another node, kube-apiserver was running fine. Another interesting data point is that according to the logs it seemed like two apiservers were running simultaneously (which shouldn't happen) until one of them shut down with the error.

**To Reproduce**

Unclear, it happened during a 3-node robotest upgrade.

**Expected behavior**

**Logs**

[10.142.15.236-planet-journal-export.log.gz](https://github.com/gravitational/gravity/files/4294397/10.142.15.236-planet-journal-export.log.gz)
[10.142.15.238-planet-journal-export.log.gz](https://github.com/gravitational/gravity/files/4294399/10.142.15.238-planet-journal-export.log.gz)

To view logs, unzip and:

```
cat ./planet-journal-export.log | /lib/systemd/systemd-journal-remote -o ./journal/system.journal -
journalctl -D ./journal ...
```

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]:
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by wadells** [comment]
I hit this in `version/6.1.x` for 5 different upgrade scenarios, all 5.5.x versions -> 6.1.latest

https://github.com/gravitational/gravity/pull/1203#issuecomment-595356917

This appears to be flaky, two of the failed scenarios were successful upon a later retry.

**Comment by wadells** [comment]
I believe your work in https://github.com/gravitational/planet/pull/575 is to mitigate this issue @a-palchikov.  If I'm mistaken, you're welcome to un-assign.

**Comment by a-palchikov** [comment]
@walt - yes, this is my wip.

**Comment by wadells** [comment]
Triaging robotest runs from 03-11 to 03-24 showed 95 (probable) occurrences of this: [link](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-24T22:23:35.811000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0AAND%20timestamp%20%3E%3D%20%222020-03-11T00:00:00-08:00%22%0AAND%20timestamp%20%3C%3D%20%222020-03-25T00:00:00-08:00%22%0AAND%20NOT%20labels.__name__:%22pithos%22%0AAND%20NOT%20labels.__name__:%22stolon%22%0AAND%20jsonPayload.error:%22ContinueRetry(status%20not%20ready%20on%20some%20nodes)%22%0AAND%20jsonPayload.message:%22upgrade%22)

**Comment by r0mant** [comment]
Done in 5.5, tracking forward-ports in https://github.com/gravitational/gravity/issues/1740.
