### ISSUE TITLE
[BUG] Kubelet high CPU/memory usage due to cgroups leak

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1219]
**Describe the bug**

On older kernels / systemd versions, there is a bug with leaking cgroups for created pods which eventually leads to high CPU and memory usage in kubelet, up to a point where new pods can't be created due to out of memory issues.

This is especially pronounced in clusters that spin up / tear down large numbers of pods, for example using CronJobs.

Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/64137.

**To Reproduce**

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 5.5 and above
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by knisbet** [comment]
The workaround has been patched on each of our releases now. Closing.
