### ISSUE TITLE
lint docs as part of make & CI

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#1220]
@benarent cleaned up a *ton* of latent issues in the docs in #1210, primarily thanks to [milv](https://github.com/magicmatatjahu/milv).  In order to keep things tidy, we should begin enforcing milv compatibility (and any other good mkdocs static analysis tools) in our CI job.  Without this we will regress over time, and need another bulk cleanup.

This builds off of the one-time task #877

**Comment by wadells** [comment]
In order to keep things deterministic, we'll want to only check internal links for anything that could block a PR.  On top of that we'll want an employee to manually check & fix external links a couple times a year.

**Comment by wadells** [comment]
+ @benarent and @webvictim as they started this work with teleport.

**Comment by wadells** [comment]
I have a spitball implementation of this at https://github.com/gravitational/gravity/tree/walt/docs-build.

The juicy commit is:

https://github.com/gravitational/gravity/commit/23d64fd6bf50dacabfe779982d8515f1b9490cf3

Though this is built on top of some substantial other work.

**Comment by wadells** [comment]
Further work on this today.  I unfortuantely found jenkins has a rather stale version of docker build, missing the `--iidfile` flag which my patch stack uses.

**Comment by wadells** [comment]
With #1231 in, I just need to enable the CI job in jenkins and this will be done.

Until then `make docs` now uses `mkdocs --strict` and `make docs-lint` will call `milv -ignore-external`

**Comment by wadells** [comment]
@r0mant helped me set up the webhook for this today.   The docs CI job is now live, as seen in https://github.com/gravitational/gravity/pull/1257.

**Comment by benarent** [comment]
Nice, this is awesome. If you have any spare cycles, would you be able to port this over to Teleport.
