### ISSUE TITLE
[report] Add plain-text output of k8s resource queries

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1264]
### Description
I've recently updated the `report` command to generate the cluster dump as provided by kubectl:
```
kubectl cluster-info dump --output-directory=/path/to/output/dir --output=json
```
which dumps debugging information about all resources (incl. container logs). The change affected the usability of logs as plain-text resource descriptions (pods/nodes/events etc.) are also helpful.

Additionally, with the move to [logrange](https://github.com/logrange/logrange), `report` is no longer capturing the collected logs.

### Suggestion
 * Revert the changes to continue dumping resources descriptions in plain-text as before (alongside the `cluster-info dump`).
 * Capture the logs as collected on the cluster and include in the debug report.

**Comment by r0mant** [comment]
Closed by https://github.com/gravitational/gravity/issues/1264.
