### ISSUE TITLE
Improve Gravity report capabilities 

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1273]
Gravity debug package is several gigabytes and takes customers sometimes 30-60 mins to capture the whole package. Currently, lacks any customization or possibility in running a filtered type report. 

Some use cases to extend capabilities of Gravity report:

- [x] Collect logs from a specific node or subset of nodes
- [ ] Collect specific components logs i.e. flannel, etcd, etc.
- [x] An option to collect logs from a provided interval i.e. last 1 hour etc. (also discussed in #1177)
- [ ] An option to generate lightweight/filtered report vs full debug package report
- [x] Add a few more system collectors that have come up recently:
  - [x] Reboots history: `last -x`
  - [x] Kernel information: `uname -a`
  - [x] Serf cluster: `serf members`
  - [x] Swap status: `swapon -s` (we have vmstat but wouldn't hurt)
  - [x] Etcd metrics: `curl -s --insecure --tlsv1.2 --cacert /var/state/root.cert --cert /var/state/etcd.cert --key /var/state/etcd.key https://localhost:4001/metrics`

**Comment by a-palchikov** [comment]
Collecting logs from specific nodes can be done with a low-level `gravity system report` that is not cluster-aware - i.e. by running it on the specific node.
The targeted reporting is also supported to a degree with `gravity system report --filter=<filter>` where `filter` is one of `etcd` / `kubernetes` / `system`.
