### ISSUE TITLE
[BUG] Planet agent connection leak

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1280]
**Describe the bug**

It was reported that planet agents keep tons of open connections to other planet agents that aren't being closed and eventually leads to "too many files" errors.

As an idea, some grpc clients in satellite don't use contexts properly at the moment which can lead to hanging connections.

**To Reproduce**

**Expected behavior**

Satellite doesn't leak connections.

**Logs**

Some `lsof` stats:

```
 760158 3510
   7061 8758
   5508 2445
```

The first process is a planet agents that keeps 760K open connections to other agents:

```
  13554 ip-xxx.ec2.internal:SRC->ip1:7575 (ESTABLISHED)
  14796 ip-xxx.ec2.internal:SRC->ip2:7575 (ESTABLISHED)
  14796 ip-xxx.ec2.internal:SRC->ip3:7575 (ESTABLISHED)
  14796 ip-xxx.ec2.internal:SRC->ip4:7575 (ESTABLISHED)
  14823 ip-xxx.ec2.internal:SRC->ip5:7575 (ESTABLISHED)
```

Some errors/timeouts are visible in the agent logs:

```
Mar 21 18:20:32 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: WARN             Timed out collecting node statuses: context deadline exceeded. agent/agent.go:481
Mar 21 18:20:32 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: WARN             Timed out collecting test results: context deadline exceeded. agent/agent.go:338
Mar 21 18:20:32 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: ERRO [TIME-DRIF] rpc error: code = DeadlineExceeded desc = context deadline exceeded monitoring/timedrift.go:130
Mar 21 19:20:09 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: ERRO [TIME-DRIF] rpc error: code = DeadlineExceeded desc = context deadline exceeded monitoring/timedrift.go:130
Mar 21 19:20:09 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: WARN             Timed out collecting test results: context deadline exceeded. agent/agent.go:338
Mar 21 19:20:09 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: WARN             Timed out collecting node statuses: context deadline exceeded. agent/agent.go:481
Mar 21 20:25:49 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: WARN             Timed out collecting node statuses: context deadline exceeded. agent/agent.go:481
Mar 21 20:26:49 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: WARN             Timed out collecting node statuses: context deadline exceeded. agent/agent.go:481
Mar 21 21:20:52 ip-10-35-2-179.ec2.internal /usr/bin/planet[29702]: WARN             Timed out collecting node statuses: context deadline exceeded. agent/agent.go:481
```

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 6.1 and later, likely 5.5 as well.
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by bernardjkim** [comment]
Looking at `monitoring/timedrift`
I think there might be a problem with `getAgentClient` due to a bug in TTLMap.
```golang
// getAgentClient returns Satellite agent client for the provided node.
func (c *timeDriftChecker) getAgentClient(ctx context.Context, node serf.Member) (client.Client, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	clientI, exists := c.clients.Get(node.Addr.String())
	if exists {
		return clientI.(client.Client), nil
	}
	client, err := c.DialRPC(ctx, &node)
	if err != nil {
		return nil, trace.Wrap(err)
	}
	if err := c.clients.Set(node.Addr.String(), client, clientsCacheTTLSeconds); err != nil {
		return nil, trace.Wrap(err)
	}
	return client, nil
}
```
https://github.com/mailgun/holster#expirecache
TTLMap specifies that a call to `Get` will reset the expiry time of the element. But after looking through the code and doing some testing, that doesn't seem to be the case. `Get` is not updating the expiry time of an element.

So that would mean that `getAgentClient` will be creating a new client every hour and we are not currently closing client connections for clients that have expired from the cache.

**Comment by r0mant** [comment]
@bernardjkim Good catch! When working on this, let's do the following:
* Make sure that this is indeed the culprit.
* ExpireCache looks interesting, just looking at its usage docs doesn't seem to be very convenient to use though (needing to call Each and/or having a separate goroutine) and not very clear how to determine the item has expired. Maybe we could do something simpler? Like, just store all clients in a regular map (no TTL) and compare with a list of existing serf members and close clients which aren't there?
* Let's still make sure our "makeClient" correctly accepts/propagates/uses the context and it is properly closed everywhere.

**Comment by bernardjkim** [comment]
I think this issue should be resolved now. I might be able to make a more solid claim if more information was provided, so this is just my educated guess as to how this issue occurred.

If this cluster is running an older version of gravity, the `getAgentClient` may not be dialing with a context or closing connections. This is from satellite version <= 6.1.2.
```golang
// getAgentClient returns Satellite agent client for the provided node.
func (c *timeDriftChecker) getAgentClient(node serf.Member) (agent.Client, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	clientI, exists := c.clients.Get(node.Addr.String())
	if exists {
		return clientI.(agent.Client), nil
	}
	client, err := c.DialRPC(&node)
	if err != nil {
		return nil, trace.Wrap(err)
	}
	c.clients.Set(node.Addr.String(), client, time.Hour)
	return client, nil
}
```

If we were to introduce a network partition into this cluster:
- Calls to `getAgentClient` will end up waiting on `DialRPC` indefinitely. 
- No client connections will be stored in the cache so `DialRPC` will be called every status update cycle (~30 seconds).
- When the network partition is finally removed, all the queued up `DialRPC` calls can return a client connection.

Looking at the information above, we have a 5 node cluster and 760k open connections. If our reasoning above makes sense. Each time the time-drift checker is run, it should create 8 new connections (4 from node to peers and 4 from peers to node). The checker is run every 30 seconds. so it would take ~33 days to have created 760k connections, which isn't an unreasonable amount of time...

**Comment by r0mant** [comment]
After investigation and trying to reproduce @bernardjkim and I think that this should be fixed since planet agent now propagates contexts everywhere properly. Will monitor if this reappears.
