### ISSUE TITLE
Setup default storage class

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1284]
When OpenEBS is enabled, Gravity clusters include two storage classes out of the box, openebs-hostpath and openebs-device, but there's not default storage class which means that a user has to specify storage class explicitly in their claim. To improve UX in this area we could do the following:

* Make "openebs-hostpath" the default storage class since it always works.
* Add a note to the Persistent Storage section of our docs about default storage class and changing the default storage class: https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/.

**Comment by denniswebb** [comment]
I have added the following to my install hook script to accomplish this for now.
`kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`

**Comment by eldios** [comment]
Thanks for your contribution @denniswebb ... I'm going to resume working on this soon and definitely going to take your suggestion into account. Thanks again!
