### ISSUE TITLE
Ability to tell the upgrade script to only upgrade master

### ISSUE THREAD

**Issue by helgi** [gravitational/gravity#1289]
The `./upgrade` script that comes in the tarball, I would like to be able to instruct it to only upgrade masters with `--masters-only` (or similar) flag with the intent of rolling `workers` myself with a different mechanism.

I can see this working well with compatible gravity and kubernetes versions but perhaps use the upgrade path support logic that was developed to determine if 5.1 can upgrade to 6.3 (with its in-between versions). In the case of incompatible behaviour fail the `upgrade` or have a flag to do a full upgrade?

**Comment by r0mant** [comment]
This is an interesting idea. I'm curious, what is the specific use-case for using different mechanism for upgrading workers? To me it sounds like if the current algorithm is not good enough, Gravity should do a better job at rolling them then :)

**Comment by helgi** [comment]
The way it works for me is to update `gravity` we bake a new AMI and if the new AMI has a newer gravity we kick off the upgrade (it compares cluster gravity with AMI gravity) as part of `cloud-init`. 

The new AMI also causes a full autoscaling group (ASG) roll which terminates nodes, it will pause when it sees `gravity status` turning to `upgrading` so it isn't being disruptive. Gravity upgrade will drain, upgrade and uncordon nodes; a 20 worker cluster can take ~1 hour to just do that. And then the nodes will be drained and rolled again due to the ASG picking back up.

Due to how we roll AMIs it is more efficient for me to bring up net new workers when possible as I get the same end result :) But I also made the caveat about the version disparity might be an issue (i.e. 5.1 -> 6.1 or some)

The issues with the current gravity approach you could consider to improve:
1. Better information when a plan fails, inform people `gravity upgrade trigger` with flags can help recover/continue
2. The `gravity plan` for upgrade is static, if a node is shutdown (variety of reasons, including AWS just plain retiring a node) can make an update fail as it is expecting to talk to node 1234. It should be fine if a node is no longer available, somehow.
3. `gravity plan` could be more dynamic; spin-off sub-operations per grouping (f.ex. each node upgrade)
4. Ability to upgrade masters and workers independently (expansion on this ticket)

To summerize I think there are opportunity for improve algo around this but also providing more granular control of order of operations for cases like I describe above, a more "cloudy" roll if you will :)

**Comment by helgi** [comment]
another additive, as `cluster-autoscaler` can be the culprit sometimes in scaling nodes down (if it isn't AWS retiring, etc, etc)

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-a-particular-node

Gravity could run the following at the start of an upgrade: `kubectl annotate node cluster-autoscaler.kubernetes.io/scale-down-disabled=true --all` and then `kubectl annotate node cluster-autoscaler.kubernetes.io/scale-down-disabled- --all` at the end. 

This can help keep the plan list stable, in case a customer has installed https://github.com/kubernetes/autoscaler

**Comment by a-palchikov** [comment]
@helgi I did not quite understand the bit about your bringing in the new workers - does it simply mean they're stateless and replaceable or that you want another level of control? If the workers are replaceable and stateless, simply removing them from the cluster prior to upgrade should have the same result as running with `--masters-only`?

**Comment by helgi** [comment]
Removing workers from the cluster prior upgrade is not an option as that sounds like downtime of the whole application setup on the cluster. 

The reason I suggested `--masters-only` is because workers are removed/added, one by one, a worker is terminated (which does kubectl drain and gravity remove), a new one is brought up by the AWS Autoscaling, joining the cluster which would result in workers joining with the newer Gravity binary if the masters have been upgraded already.

**Comment by a-palchikov** [comment]
So, this hints at the operation plan, that you can run in groups (in case of multi-hop upgrades) - roll out all masters to k8s version X, have workers replaced one by one, then roll out masters to X+1 and so on?

**Comment by helgi** [comment]
Yeah, in a way. I'd want to handle the workers outside the scope of the `upgrade` with my own mechanisms but what you said is more or less the path I am looking for. It's basically a smaller scope `upgrade` that still runs from `init` all the way to `gc` but only against masters.

Only time I see it be a real issue is if an upgraded set of masters go so far ahead that workers can not longer join the masters.
