### ISSUE TITLE
[BUG] Hub certificates intermittently resetting

### ISSUE THREAD

**Issue by tosih** [gravitational/gravity#1295]
**Describe the bug**
We seem to have a recurring issue happening on our OpsCenter clusters running Gravity 6.3.5-6. After about of month of operation, the tls certificate seems to reset itself. As a result, we cannot communicate with the k8s cluster without setting an `--insecure-skip-tls-verify` flag. Without this, our deployments have been failing, for clear reasons.

```
ツ kubectl get pods -n core-paas
Unable to connect to the server: x509: certificate is valid for ip-10-1-0-94.ec2.internal, leader.gravity.local, leader.telekube.local, apiserver, registry.local, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster, kubernetes.default.svc.cluster.local, ip-10-1-0-94.ec2.internal, not opscenter.opscenter.cpdev.msap.io
```

This has happened to multiple clusters in the past couple weeks, in an intermittent fashion. The only fix we have been able to acertain is to replace the entire cluster. This only has been happening recently to OpsCenter clusters.

**To Reproduce**
OpsCenter cluster running Gravity 6.3.5 -> 6.3.6 will randomly lose signed certificate

**Expected behavior**
Certificate used by gravity should remain valid with signed certificate

**Logs**
Gravity report already uploaded to Kevin.

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Centos 7.5
 - Gravity [e.g. 5.5.4]: Gravity 6.3.5 & 6.3.6
 - Platform [e.g. Vmware, AWS]: AWS

**Additional context**
The nodes had been untouched for 39 days.

Invalid cert missing SANs:
```
X509v3 Subject Alternative Name: 
    DNS:ip-10-1-0-94.ec2.internal, DNS:leader.gravity.local, DNS:leader.telekube.local, DNS:apiserver, DNS:registry.local, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc.cluster.local, DNS:ip-10-1-0-94.ec2.internal, IP Address:127.0.0.1, IP Address:127.0.0.2, IP Address:10.1.0.94, IP Address:10.100.0.1
```

Valid cert SANs:
```
X509v3 Subject Alternative Name: 
    DNS:ip-10-30-4-230.ec2.internal, DNS:leader.gravity.local, DNS:leader.telekube.local, DNS:apiserver, DNS:registry.local, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc.cluster.local, DNS:ip-10-30-4-230.ec2.internal, DNS:opscenter.opscenter.example.com, DNS:opscenter.opscenter.example.com, DNS:opscenter.10.30.4.230, IP Address:127.0.0.1, IP Address:127.0.0.2, IP Address:10.30.4.230, IP Address:10.100.0.1
```

**Comment by helgi** [comment]
Unclear if this is related but when `hub` gets rolled (masters) one at a time, at the end we lose the certificates as well. When doing the same on a non-`hub` we never lose information, trusted cluster info sticks around and so on.

Perhaps certs and other `hub` related items aren't stored in a durable/replicated manner?

I have had various discussions with @knisbet and @r0mant but we never came to a conclusion around it.
