### ISSUE TITLE
[BUG] Timeouts on join if icmp is blocked between nodes

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#1329]
Sorry, this is a verbal report from a customer, I don't have any logs or repro steps just yet. 

According to customer S, they see failures in the join process due to some sort of timeout, if ICMP isn't enabled between hosts. This was reported to be related to a ping, however, based on the discussion I suspect it's more likely when the join process tests the endpoints for whether it's joining a cluster or installer, that  it times out trying to reach those endpoints if an ICMP port unreachable isn't received to immediately indicate the connection attempt failed.

So we need to validate the timeouts operate correctly in join (both existing and installer), if icmp port unreachable messages are not received.

**Comment by aelkugia** [comment]
Marking as closed after discussion w/ customer S - this is no longer an issue for them.
