### ISSUE TITLE
Extend License generation UI in Gravity Hub

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1354]
Hub UI License generation should be extended to include the below currently missing fields - that are available by tag in CLI:

- customer name
- customer email
- product name
- product version
- encryption key

Currently, Hub UI allows for the following:

- Maximum Number of Nodes
- Expiration date

**Comment by federicoboerr** [comment]
All these are metadata that we add to the license.
So the actual request would be to be able to configure metadata as the command line allows to.
Also, maybe as another issue, it's really important that any license generation event gets audited and the audit is accessible from the UI.
