### ISSUE TITLE
[BUG] Able to publish gravity artifacts even though invalid tag is provided

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/gravity#1362]
**Describe the bug**

Gravity-Publish-5.2 job succeeds even though an invalid tag was provided for the monitoring-app. The job expected monitoring-app version 6.0.7 to be available, but that tag was not yet created. Git fetch fails, but the build continues and publishes the current master branch instead. We have not tested behavior with other artifacts, but they may have the same issue as well.

**To Reproduce**

Update the monitoring-app in gravity's Makefile. Set it to an invalid tag. Then run Gravity-Publish-5.2 job.

**Expected behavior**

Gravity-Publish-5.2 job should fail.

**Logs**

https://jenkins.gravitational.io/view/Publishing/job/Gravity-Publish-5.2/119/console

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]:
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by UnderGreen** [comment]
Fixed in 6.1.x, 7.0.x and master branches.
