### ISSUE TITLE
Consider enforcing a reasonable DefaultTasksMax

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1399]
It has been observed on one of the client clusters, where installer ran into issues with being unable to execute processes. The host was refusing to run commands with an error message stating that it was unable to `fork`.
The culprit seems to have been the low setting for `DefaultTasksMax` in [systemd](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html#DefaultTasksMax=) which was set to `512`.

Consider suggesting a higher default for this and validating the low values with a pre-flight check.

**Comment by knisbet** [comment]
Some of the symptoms are that the systemd scope unit for planet get's created with 512 tasks, which isn't really enough to run a complex app.

```
/sys/fs/cgroup/pids/system.slice/-planet-0e6a5905-3c44-4af3-a8b4-5e275c5a6630.scope/pids.max:512
/sys/fs/cgroup/pids/system.slice/-planet-0e6a5905-3c44-4af3-a8b4-5e275c5a6630.scope/pids.current:317
```

**Comment by knisbet** [comment]
Fixed in
- https://github.com/gravitational/planet/pull/604
- https://github.com/gravitational/planet/pull/607
- https://github.com/gravitational/planet/pull/608

**Comment by wadells** [comment]
> * [gravitational/planet#607](https://github.com/gravitational/planet/pull/607)

is in planet 7.1.0+, which is as of yet unreleased, but will cover all future versions of gravity
> * [gravitational/planet#608](https://github.com/gravitational/planet/pull/608)

is in planet 7.0.25+, which is gravity 7.0 series, 7.0.3+
> * [gravitational/planet#604](https://github.com/gravitational/planet/pull/604)

is in planet 6.1.21+, which is gravity 6.1 series, 6.1.25+
