### ISSUE TITLE
Validate CentOS 7.8

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1402]
CentOS 7.8 is out - we should see if our active Gravity versions can install there and add it to our docs.

**Comment by r0mant** [comment]
@aelkugia Where did you see it's out? 7.8 does not seem to be out yet: https://wiki.centos.org/Download.

**Comment by UnderGreen** [comment]
I think the task is about RH 7.8. Centos will be available in May/June.

**Comment by r0mant** [comment]
We have another ticket about RHEL7.8 (https://github.com/gravitational/gravity/issues/1330), closing this one then.

**Comment by aelkugia** [comment]
I saw it was pushed to the CR repo on 4/8 so I was reading it was now available to update existing installations. Still not available to GA though so I assume we can reopen at that time or create a new ticket.
