### ISSUE TITLE
[BUG] Cluster degrades during rolling update due to nethealth failure

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/gravity#1403]
**Describe the bug**

The cluster ends up in a degraded state while doing a rolling update of the cluster. After updating a master node, the rest of the nodes in the cluster become degraded due to `nethealth` failure. All nodes show overlay network issue with the master node that was replaced.

EDIT:
After more investigation, the root cause seems to be that nethealth pods persist prometheus metrics for nodes that are no longer part of the cluster. Currently, if a node is having overlay network issues, and then removed from the cluster, that node's metrics will be frozen in that state. The nethealth checker will continue pulling metrics for that node and will stay degraded forever.

**To Reproduce**

- Setup multi-node cluster.
```
[vagrant@node-1 ~]$ sudo gravity status
Cluster name:           dev.test
Cluster status:         active
[...]
Cluster nodes:
    Masters:
        * node-1 (172.28.128.101, node)
            Status:     healthy
        * node-2 (172.28.128.102, node)
            Status:     healthy
        * node-3 (172.28.128.103, node)
            Status:     healthy
```

- Degrade nethealth checker using iptables to drop traffic from one node to another
```[vagrant@node-1 ~]$ sudo iptables -A INPUT -p udp -s 172.28.128.102 -j DROP```

- Once nodes are in a degraded state due to nethealth checker remove one of the degraded nodes. 
```[vagrant@node-1 ~]$ sudo gravity remove node-2 --force```

- Checking gravity status after the node is removed gives us
```
[vagrant@node-1 ~]$ sudo gravity status
Cluster name:           dev.test
Cluster status:         degraded
[...]
Cluster nodes:
    Masters:
        * node-1 (172.28.128.101, node)
            Status:     degraded
            [×]         overlay packet loss for node 172.28.128.102 is higher than the allowed threshold of 20.00%: 100.00% ()
        * node-3 (172.28.128.103, node)
            Status:     healthy
```

**Expected behavior**

Cluster should not degrade during this update scenario. 

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: 
 - Gravity [e.g. 5.5.4]: 5.5.40
 - Platform [e.g. Vmware, AWS]: 

**Additional context**

**Comment by r0mant** [comment]
Nethealth checker was temporarily excluded from the planet agent (but the checker itself is still running) so it does not affect the cluster status. It will be reenabled back as a warning once we've addressed the issues with it.
