### ISSUE TITLE
[Enhancements] Extend capabilities of log forwarder

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1476]
Currently, the log forwarder sends logs to the server with the pod id of the forwarder and app. On the server-side, it's hard to identify which application the logs come from. Some mentions of having the forwarder be more configurable/enhancements of log forwarder including:

- Have more attributes in logs forwarded, like the namespace id, deployment name (app name), so the server can identify which application the log comes from

- Filter out unnecessary logs and only send the application logs to the server, including sending only specific containers' log in a pod

- Configure log format with a pre-defined template, which is compatible with the popular log server formats, particularly the GELF (Graylog Extended Log Format)

**Comment by a-palchikov** [comment]
This should also include [support](https://www.rsyslog.com/using-tls-for-receiving-log-messages/) for TLS as this has been requested previously.
