### ISSUE TITLE
[BUG] UI date format is not following US standard

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1489]
**Describe the bug**

Should be MM/DD/YYYY but currently it's DD/MM/YYYY.

<img width="210" alt="Screen Shot 2020-05-01 at 2 40 36 PM" src="https://user-images.githubusercontent.com/339322/80844093-bbd99c00-8bba-11ea-9780-1162d1f0c2a5.png">

**To Reproduce**

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 7.x
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by webvictim** [comment]
Might I recommend https://en.m.wikipedia.org/wiki/ISO_8601 ?

The US is basically the only place in the world that does dates this way. It’s confusing for anyone who isn’t there.

**Comment by r0mant** [comment]
@webvictim Believe me, I feel your pain :) That said, I think 95% of our customers are US-based so I think that the current format (with the bug fixed, that is) is a logical choice (and IIRC it was consciously chosen before).
