### ISSUE TITLE
[BUG] 7.0.X Monitoring doesn't provide Compute Resource/Pod

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/gravity#1506]
**Describe the bug**
Pod CPU and memory monitoring is not being provided in 7.0 within prometheus.  That prevents monitoring and usage of horizontal pod autoscaler.

**To Reproduce**
 Deploy a cluster with 7.0.X. The below command will not return metrics for pods within those namespaces.  6.X does return metrics for this.

kubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/kube-system/pods/" 
kubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/" 

Also view the Compute Resources /Pod page within the Monitoring screens.

**Expected behavior**
Expect to get this kind of output:
```
{“kind”:“PodMetrics”,“apiVersion”:“metrics.k8s.io/v1beta1 13”,

“metadata”:{“name”:“podname”,“namespace”:“default”,“selfLink”:"/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/podname",

“creationTimestamp”:“2019-06-26T03:41:25Z”},“timestamp”:“2019-06-26T03:41:00Z”,“window”:“1m0s”,

“containers”:[{“name”:“cassandra”,“usage”:{“cpu”:“4m”,“memory”:“816388Ki”}}]}
```

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: ubuntu 18.04
 - Gravity [e.g. 5.5.4]: 7.0.4
 - Platform [e.g. Vmware, AWS]: GCP

**Comment by r0mant** [comment]
This was addressed in [7.0.5](https://gravitational.com/gravity/docs/changelog/#705-may-13th-2020), to resolve this entirely:

- [ ] @r0mant to review https://github.com/gravitational/monitoring-app/pull/162.
- [ ] @UnderGreen to merge ^ and update monitoring-app in master.
- [ ] @UnderGreen to double-check if this was done in 6.1.

**Comment by stevenGravy** [comment]
@r0mant  I am seeing metrics in 7.0.11.  This can be closed for 7.

**Comment by r0mant** [comment]
@UnderGreen I'm gonna close this ticket, added ports to 6.1 (to double-check) and master to our meta tracking ticket: https://github.com/gravitational/gravity/issues/1740.
