### ISSUE TITLE
[BUG] robotest failures on 6.3.x: no such function: "upgrade"

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#1508]
**Describe the bug**
Robotest on `versions/6.3.x` is failing with:

```
19:31:46 [robotest] --- FAIL: TestMain (0.00s)
19:31:46 [robotest]     suite_test.go:82: failed to parse args: no such function: "upgrade", no such function: "upgrade"
```

**To Reproduce**
Open a PR against branches/6.3.x after #1425 merged (a8699c9).  For instance: #1504

**Expected behavior**
I expect robotest execute smoothly on PR builds.

**Logs**
See https://jenkins.gravitational.io/job/Gravity-PR-5.2/view/change-requests/job/PR-1504/1/

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: those configured in https://github.com/gravitational/gravity/blob/a8699c990cbbf228fce72d2fc55bb636e2f0a717/build.assets/robotest_run_suite.sh
 - Gravity [e.g. 5.5.4]: 6.3.15-2
 - Platform [e.g. Vmware, AWS]: Jenkins/CI/GCP

**Comment by wadells** [comment]
The origin of this is the partial port of  #1312 in #1425 seen at:

in https://github.com/gravitational/gravity/pull/1425/commits/a5f813ef5950ed3b3f91c3f458ae755290739655

Specifically, this changed the upgrade test declaration & robotest tag in `build.assets/robotest_run_suite.sh` but this tag was/is overriden by the jenkins parameter ROBOTEST_VERSION (set to `stable-gce`), and thus the `dima` version in `build.assets/robotest_run_suite.sh` is ignored.  This creates a mismatch between upgrade test declaration & robotest version.

I'm not sure how this PR passed the Jenkins PR build -- it should have failed without manually tinkering with the parms in jenkins.  Unfortunately this history is lost to ghprb: 

https://jenkins.gravitational.io/job/Gravity-PR-5.2/job/PR-1425/5/display/redirect

**Comment by wadells** [comment]
Concerningly, I believe the `gce-stable` tag was change in quay.io, allowing https://jenkins.gravitational.io/job/Gravity-PR-5.2/view/change-requests/job/PR-1504/4/ to pass with no source changes.  However, this will push the problem from only 6.3 to every branch that references `stable-gce`.

**Comment by wadells** [comment]
From https://quay.io/repository/gravitational/robotest-suite?tab=history

```
stable-gce was moved to SHA256 09f13ec0f869 from SHA256 e3de50d7ec88 Wed, May 6, 2020 1:37 PM
```

Looks like this also applies to https://quay.io/repository/gravitational/robotest-e2e?tab=history

There are also some other suspicious tag moves:

```
uid-gid was moved to SHA256 003c3e4143a1 from SHA256 273b3d59c3ae Fri, May 1, 2020 5:11 AM
1.0.219 was moved to SHA256 003c3e4143a1 from SHA256 fe8c15df05a9 Fri, May 1, 2020 5:10 AM
```

Working on restoring these to their original versions currently.  From a systemic point, I want to see if quay.io has a way to prevent moving tags (especially those matching a version number).

**Comment by wadells** [comment]
> From a systemic point, I want to see if quay.io has a way to prevent moving tags (especially those matching a version number).

Looks like this isn't possible currently:

https://devops.stackexchange.com/questions/9711/how-to-enable-tag-immutability-in-quay-io

I haven't found anything poking around the admin interface either.  Looks like if we want to avoid this, it'll be soft enforced in the release automation.

**Comment by wadells** [comment]
I reverted `stable-gce` and `uid-gid` back to their original locations:

```
uid-gid was reverted to SHA256 273b3d59c3ae from SHA256 003c3e4143a1  Wed, May 6, 2020 6:35 PM
stable-gce was reverted to SHA256 e3de50d7ec88 from SHA256 09f13ec0f869 Wed, May 6, 2020 6:34 PM
```

I didn't mess with `1.0.2191` because it isn't likely that this is used anywhere and it corresponds to one of @a-palchikov's releases.

**Comment by wadells** [comment]
If we want to rollback, we can revert https://github.com/gravitational/gravity/commit/a8699c990cbbf228fce72d2fc55bb636e2f0a717

If we want to roll forward, https://github.com/gravitational/gravity/pull/1507 has the correct fix here.

**Comment by r0mant** [comment]
Thanks @wadells for taking care of this. I'm fine with merging your pull request as it's probably the proper way. Things should get more predictable when we migrate robotest to stable semver versioning scheme.

**Comment by wadells** [comment]
Reverting `uid-gid to 003c3e4143a1` removes two things from gravity branches that reference it:

selinux auto enablement : https://github.com/gravitational/robotest/commit/f27079bfac827d7fc272547377ac2c550a0a8856
newer images: https://github.com/gravitational/robotest/commit/137c4df6d51541e6a7c42535d5a5344540681b0f

This will result in reduced coverage (we'll get it back soon) and shoudln't break anything.

I'm mixed if reverting this was a good idea immediately.  It unnecessarily increases the blast radius for mitigating this bug, but it also is the right expectation to set long term.

**Comment by wadells** [comment]
> Reverting `uid-gid to 003c3e4143a1` removes two things from gravity branches [...]
> 
> I'm mixed if reverting this was a good idea. It unnecessarily increases the blast radius for mitigating this bug, but it also is the right expectation to set long term.

It was not a good idea. Reverting `uid-gid` resulted in https://github.com/gravitational/gravity/issues/1511, resulting in an extra 16 hours of disruption overnight.
