### ISSUE TITLE
Synchronize status query with controller

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1521]
## Current Result

Currently the CLI status query is detached from the cluster controller which runs a couple of additional status checks and this can lead to situations when `gravity status` is reporting `healthy` for all nodes with cluster state being `degraded` for no obvious reason.
The reasons might be:
  * the controller has not synced up internal cluster status
  * the controller's status hook is failing

 ## Expected Result

  * `gravity status` attempts to sync status via the cluster controller if possible
  * if not possible, it should revert to old behavior of querying all possible data points
  * `gravity status` should indicate whether the cluster is failing in the application status hook
  * bonus if we can additionally make it super obvious if the status is failing while the agent is not running/down

This is one of the reasons why querying status prior to upgrade and getting healthy still leads to robotest failures during upgrade since the cluster status loop has not synced the cluster state yet.

**Comment by knisbet** [comment]
This comes up with customers a lot as well, where they'll see degraded after recovering a problem but no checker failures. Another item we should consider, is gravity status is slowly evolving to pull status from more and more endpoints (satellite, alertmanager, I think kubernetes, etc), which seems to be getting slow.

**Comment by wadells** [comment]
If you work on this issue, please take a look at #1641 too, as it seems topically similar.
