### ISSUE TITLE
Verify Gravity on SLES 15

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1582]
SLES 12 general support ended in December 2019. We should see if Gravity can install on SLES 15 and add it to our releases table.

**Comment by sandhujasmine** [comment]
Thanks @r0mant - it would also be useful to know what happens if OS is updated with gravity 6.1.x already installed on SLES12. I expect it to continue working post upgrade, but this would be useful for folks who need to upgrade an existing installation.

**Comment by wadells** [comment]
Results from today: Gravity 6.1.x prior to 6.1.25 will hit #1399 on SUSE12 sp5 unless the DefaultTasksMax in [systemd](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html#DefaultTasksMax=)  are bumped.

I've got a battery of automated tests running overnight exercising all of our commonly tested scenarios on 6.1.28.

I'll take a further look at these results as well as some earlier 6.1.x versions tomorrow.

**Comment by wadells** [comment]
I've done hand/one-off checks SUSE12 sp5 with Gravity  6.1.9. 6.1.13 and 6.1.28, and with our standard battery of tests.  We're safe to add  SUSE12 sp15 to Gravity 6.1's supported distros, with the caveat of requiring 6.1.25+ or a workaround for #1399.

I'll invest in SUSE 15 testing & automation next week.
