### ISSUE TITLE
[BUG] Timedrift checker shows errors during join

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1595]
**Describe the bug**

When adding a new node, while the operation is still going, gravity status shows the following picture (`g5-cluster-node-2` is being added):

```
Cluster nodes:
    Masters:
        * node-1 (10.128.0.16, node)
            Status:		degraded
            [×]			failed to check time drift (rpc error: code = DeadlineExceeded desc = context deadline exceeded)
            Remote access:	online
        * node-3 (10.128.0.20, node)
            Status:		degraded
            [×]			failed to check time drift (rpc error: code = DeadlineExceeded desc = context deadline exceeded)
            Remote access:	online
        * g5-cluster-node-2 (10.128.0.18, node)
            Status:		degraded
            [×]			etcd-healthz (unexpected HTTP status: Service Unavailable)
            Remote access:	online
```

Looks like the timedrift checker tries to contact the new node too soon and fails, the following errors can be seen in the logs:

```
May 21 16:09:01 node-1 /usr/bin/planet[745]: ERRO [TIME-DRIF] rpc error: code = DeadlineExceeded desc = context deadline exceeded monitoring/timedrift.go:123
May 21 16:09:31 node-1 /usr/bin/planet[745]: ERRO [TIME-DRIF] rpc error: code = DeadlineExceeded desc = context deadline exceeded monitoring/timedrift.go:123
```

These errors are temporary and resolve when the new node finishes joining, but nonetheless they are confusing and may give an impression that something's wrong in the cluster.

https://github.com/gravitational/gravity/issues/1552 may be referring to the same behavior and also mentions ping checker so we might need to take a look at both.

**To Reproduce**

Launch `gravity join` and observe `gravity status` during the operation.

**Expected behavior**

Satellite does not produce bogus warnings during the cluster modifications.

**Logs**

See above.

**Environment (please complete the following information):**
 - Gravity [e.g. 5.5.4]: Likely all, I saw this on latest 5.5's.

**Additional context**

**Comment by helgi** [comment]
@r0mant Looking at this ticket, I think they are the same symptom at least and as you noted there was another checker; I'm pretty certain there are at least 2 more checkers I see on occasion during mass join/remove (vs more controlled join/remove) which are also transient but I can't recall them atm

**Comment by r0mant** [comment]
Done in 5.5, forward-ports are tracked in https://github.com/gravitational/gravity/issues/1740.
