### ISSUE TITLE
[BUG] Gravity status reports State: Active even though there are failing healthchecks

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#1641]
**Describe the bug**
Robotest finds `gravity status --output=json` reporting `"state": "active"` while `"cluster_status": 2` and one or more nodes report failing healthchecks.

**To Reproduce**

Run `sudo gravity status --output=json` on a node immediately after the last install/join process exits.  The symptoms will typically resolve within seconds to minutes as the health check clears the the cluster becomes fully healthy.  This is not a 100% reliable repro, but repeatedly doing this (e.g. via the any robotest test case) will provide examples.

Let me know if you need help reproing.

Examples can be found with this [stackdriver query](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-05-29T22:43:53.856000000Z&customFacets=&limitCustomFacetWidth=true&interval=CUSTOM&scrollTimestamp=2020-05-29T11:40:55.390407209Z&dateRangeEnd=2020-05-29T22:43:43.462Z&advancedFilter=resource.type%3D%22project%22%0AjsonPayload.cmd%3D%22sudo%20gravity%20status%20--output%3Djson%20--system-log-file%3Dgravity-system.log%22%0AAND%20jsonPayload.message:%22%5C%22state%5C%22:%5C%22active%5C%22,%22%0AAND%20jsonPayload.message:%22%5C%22system_status%5C%22:2,%22).

Here is a slightly redacted status captured from gravity 6.1.27 showing the issue:
<details>
<summary><code>gravity status --output=json</code></summary>
<pre>
{
  "cluster": {
    "application": {
      "repository": "gravitational.io",
      "name": "telekube",
      "version": "6.1.27"
    },
    "state": "active",
    "domain": "robotest-unit-test",
    "token": {
      "token": "ROBOTEST",
      "expires": "0001-01-01T00:00:00Z",
      "type": "expand",
      "account_id": "00000000-0000-0000-0000-000000000001",
      "site_domain": "robotest-unit-test",
      "operation_id": "42178dd3-291c-4dd7-a870-87a1ade5d93a",
      "user_email": "agent@robotest-unit-test"
    },
    "operation": {
      "type": "operation_install",
      "id": "42178dd3-291c-4dd7-a870-87a1ade5d93a",
      "state": "completed",
      "created": "2020-05-27T21:04:41.962836059Z",
      "description": "3-node install",
      "progress": {
        "message": "Operation has completed",
        "completion": 100,
        "created": "2020-05-27T21:05:20.934000242Z"
      }
    },
    "endpoints": {
      "applications": {
        "Endpoints": [
          {
            "application": {
              "repository": "gravitational.io",
              "name": "telekube",
              "version": "6.1.27"
            },
            "endpoints": [
              {
                "name": "Gravity Control Panel",
                "description": "Local administrative user interface of this Gravity cluster\n",
                "addresses": [
                  "https://10.138.0.23:32009",
                  "https://10.138.0.53:32009",
                  "https://10.138.0.56:32009"
                ]
              }
            ]
          }
        ]
      },
      "cluster": {
        "auth_gateway": [
          "10.138.0.56:32009",
          "10.138.0.23:32009",
          "10.138.0.53:32009"
        ],
        "ui": [
          "https://10.138.0.56:32009",
          "https://10.138.0.23:32009",
          "https://10.138.0.53:32009"
        ]
      }
    },
    "Extension": {},
    "server_version": {
      "edition": "open-source",
      "version": "6.1.27",
      "gitCommit": "1787b91072d649e6fcb761c803a8690d432e07d6",
      "helm": "v2.14"
    },
    "client_version": {
      "edition": "open-source",
      "version": "6.1.27",
      "gitCommit": "1787b91072d649e6fcb761c803a8690d432e07d6",
      "helm": "v2.14"
    },
    "system_status": 2,
    "nodes": [
      {
        "hostname": "robotest-unit-test-node-1",
        "advertise_ip": "10.138.0.56",
        "role": "master",
        "profile": "node",
        "status": "degraded",
        "failed_probes": [
          "etcd-healthz (unexpected HTTP status: Service Unavailable)"
        ],
        "teleport_node": {
          "hostname": "robotest-unit-test-node-1",
          "advertise_ip": "10.138.0.56",
          "public_ip": "",
          "profile": "node",
          "instance_type": ""
        }
      },
      {
        "hostname": "robotest-unit-test-node-0",
        "advertise_ip": "10.138.0.23",
        "role": "master",
        "profile": "node",
        "status": "healthy",
        "teleport_node": {
          "hostname": "robotest-unit-test-node-0",
          "advertise_ip": "10.138.0.23",
          "public_ip": "",
          "profile": "node",
          "instance_type": ""
        }
      },
      {
        "hostname": "robotest-unit-test-node-2",
        "advertise_ip": "10.138.0.53",
        "role": "master",
        "profile": "node",
        "status": "healthy",
        "teleport_node": {
          "hostname": "robotest-unit-test-node-2",
          "advertise_ip": "10.138.0.53",
          "public_ip": "",
          "profile": "node",
          "instance_type": ""
        }
      }
    ]
  }
}
</pre>
</details>

**Expected behavior**

Based on @a-palchikov's remarks at https://github.com/gravitational/robotest/pull/233/files/c14473adfd4d94e753c9b534d7f0a2722047b66d#r432571825, the `state` field should report `degraded` if there are any failing healthchecks.

**Logs**
[stackdriver query](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-05-29T22:43:53.856000000Z&customFacets=&limitCustomFacetWidth=true&interval=CUSTOM&scrollTimestamp=2020-05-29T11:40:55.390407209Z&dateRangeEnd=2020-05-29T22:43:43.462Z&advancedFilter=resource.type%3D%22project%22%0AjsonPayload.cmd%3D%22sudo%20gravity%20status%20--output%3Djson%20--system-log-file%3Dgravity-system.log%22%0AAND%20jsonPayload.message:%22%5C%22state%5C%22:%5C%22active%5C%22,%22%0AAND%20jsonPayload.message:%22%5C%22system_status%5C%22:2,%22).

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: redhat, ubuntu, debian
 - Gravity [e.g. 5.5.4]: 5.5.41 6.1.27 7.0.6-dev 7.1/master
 - Platform [e.g. Vmware, AWS]: GCP

**Additional context**
Initially I thought this was a symptom of #1521.  After discussing with @a-palchikov I'm no longer sure that is the case, and am thus filing this as a separate bug.

**Comment by wadells** [comment]
The first logs of this in stackdriver are on May 3, 2020, as seen [here](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-06-01T16:38:59.781000000Z&customFacets=&limitCustomFacetWidth=true&interval=CUSTOM&scrollTimestamp=2020-05-03T12:28:09.358844564Z&dateRangeEnd=2020-05-03T22:43:43.000Z&advancedFilter=resource.type%3D%22project%22%0AjsonPayload.cmd%3D%22sudo%20gravity%20status%20--output%3Djson%20--system-log-file%3Dgravity-system.log%22%0AAND%20jsonPayload.message:%22%5C%22state%5C%22:%5C%22active%5C%22,%22%0AAND%20jsonPayload.message:%22%5C%22system_status%5C%22:2,%22&dateRangeStart=2020-04-01T21:43:43.000Z).  Oddly, it shows up in 5.5.41, 5.5.44-dev and 5.0 in the same day.  This seems to suggest that it may be aggravated something external to gravity.... or perhaps that that is hitting a 1 month retention limit for debug logs?

**Comment by helgi** [comment]
Looks like similar root cause as https://github.com/gravitational/gravity/issues/1552

**Comment by a-palchikov** [comment]
There seems to be a discrepancy in handling of the cluster state in `gravity status` vs `gravity status --output=json`, I'll check it out.
