### ISSUE TITLE
[BUG] 7.0.x+ gravity commands require $HOME to be set

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#1647]
When running `gravity resource create` with 7.0.x from within cloud-init can result in `no path provided and environment variable HOME is not set`

This error appears to be introduced by https://github.com/gravitational/gravity/commit/7f9fea6b21ae271a5263f62315d4eee6b80dd1a6

Automation that triggers `gravity resource create` such as cloud-init, may not be expected to have a valid HOME set in order to function.

Workaround:
Set HOME environment variable when using gravity commands via automation

**Comment by pierrebeaucamp** [comment]
fyi, can confirm that the workaround works. Thanks again @knisbet

**Comment by r0mant** [comment]
Released in [7.0.7](https://gravitational.com/gravity/docs/changelog/#707-june-9th-2020).
