### ISSUE TITLE
Intermittent etcd inavailability causes upgrade to fail to create an operation

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1659]
## Current Result
If etcd is intermittently unavailable when the upgrade is initiated, the operation might fail to create. This can be problematic if the upgrade is used from an automation script.

## Expected Result
Instead, if the issue is intermittent, retry the attempt in a loop.

**Comment by knisbet** [comment]
Do we have any insight into why etcd is going intermittently unavailable? While we should retry on failures, it seems if etcd is constantly flapping something else is also going wrong.

**Comment by a-palchikov** [comment]
IIRC the etcd was becoming unresponsive for a short period of time including the embedded health check (i.e. the etcd logs displayed it as well) failing with unable to reach server.

This was triggered by using a script to routinely perform the same set of steps:
 * pull the installer package
 * uploading the packages to cluster store
 *  trigger the upgrade operation

Before the upload is initiated (`gravity update upload`), it checks the cluster health which means the cluster is healthy prior to the steps above. Somewhere into the operation, etcd gets a busy spike (I believe it was related to read requests) and becomes reproducibly unavailable long enough for planet agent to transition the cluster to degraded.

**Comment by r0mant** [comment]
Released in [5.5.48](https://gravitational.com/gravity/docs/changelog/#5548-lts-june-15th-2020), forward-port PRs are linked above.
