### ISSUE TITLE
[ERROR]: tele build is not supported on darwin, only Linux is supported

### ISSUE THREAD

**Issue by stephenlawrence** [gravitational/gravity#168]
After installing tele on my macOS I am unable to run `tele build` to package my app. The documentation says I can package my application using macOS version of tele.

`[ERROR]: tele build is not supported on darwin, only Linux is supported`

**Comment by stephenlawrence** [comment]
[Documentation Link](https://github.com/gravitational/gravity/blob/master/docs/5.x/cli.md#tele)

**Comment by kontsevoy** [comment]
@stephenlawrence correct, this used to work. This is an unfortunate side-effect of open sourcing. We'll look into bringing back MacOS builds.
