### ISSUE TITLE
[5.5.x] intermediate upgrade from 5.0 leaves old teleport service running

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#1682]
## Current Result
When upgrading from 5.0.x -> 5.5.x, the upgrade leaves the old teleport service from 5.0.x (version `2.4.7`) active so the cluster ends up with two teleport services on the host.

###  Impact
The old teleport service does not interfere with cluster function other than logging connection errors.

## Expected Result
The upgrade properly removes the initial cluster's teleport.
Additionally, the test suite should be extended to capture this scenario.

**Comment by r0mant** [comment]
@a-palchikov Can this be closed?
