### ISSUE TITLE
[BUG] Ops Center Monitoring Console displays "Dashboard not found"

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#1695]
**Describe the bug**

Ops Center - Monitoring screen displays `Dashboard not found`. Gravity status shows everything is healthy.

**Logs**

`t=2020-06-10T05:11:17+0000 lvl=eror msg="Dashboard not found" logger=context userId=0 orgId=1 uname= error="Dashboard not found"`

`/k8s-logs-monitoring-telegraf-node-ngclr-telegraf:2020-06-05T04:25:43Z E! Error in plugin [inputs.prometheus]: error making HTTP request to http://10.134.66.132:7580/metrics: Get http://10.134.66.132:7580/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Environment (please complete the following information):**
 - Gravity version]: 5.5.28

**Additional context**

**Comment by r0mant** [comment]
Done in 5.5, forward-ports are tracked in https://github.com/gravitational/gravity/issues/1740.
