### ISSUE TITLE
[BUG] Poor gravity enter performance in Gravity 7.0.7 

### ISSUE THREAD

**Issue by tosih** [gravitational/gravity#1717]
**Describe the bug**

When using `sudo gravity enter` in the latest Gravity, the performance is very poor. Keystrokes are being missed and take seconds to appear.

**To Reproduce**

```$ sudo gravity enter```
Then type anything

**Expected behavior**

Acceptable performance when inside the gravity container

**Logs**

```
[root@ip-10-218-6-141 ~]# sudo gravity enter
                                                     ___
                                                  ,o88888
                                               ,o8888888'
                         ,:o:o:oooo.        ,8O88Pd8888"
                     ,.::.::o:ooooOoOoO. ,oO8O8Pd888'"
                   ,.:.::o:ooOoOoOO8O8OOo.8OOPd8O8O"
                  , ..:.::o:ooOoOOOO8OOOOo.FdO8O8"
                 , ..:.::o:ooOoOO8O888O8O,COCOO"
                , . ..:.::o:ooOoOOOO8OOOOCOCO"
                 . ..:.::o:ooOoOoOO8O8OCCCC"o
                    . ..:.::o:ooooOoCoCCC"o:o
                    . ..:.::o:o:,cooooCo"oo:o:
                 `   . . ..:.:cocoooo"'o:o:::'
                 .`   . ..::ccccoc"'o:o:o:::'
                :.:.    ,c:cccc"':.:.:.:.:.'
              ..:.:"'`::::c:"'..:.:.:.:.:.'
            ...:.'.:.::::"'    . . . . .'
           .. . ....:."' `   .  . . ''
         . . . ...."'
         .. . ."'     -hrr-
        .
ip-10-218-6-141:/$ k^C
ip-10-218-6-141:/$ ki
```
I was trying to type `mkdir`

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Centos 7.7
 - Gravity [e.g. 5.5.4]: Gravity 7.0.7
 - Platform [e.g. Vmware, AWS]: AWS

**Additional context**

**Comment by tosih** [comment]
Tested with and without `tsh`. Performance only improves when two sessions are open with `gravity enter`.

**Comment by knisbet** [comment]
I believe this issue has been isolate to an agent installed within the cluster, that is mounting and opening /dev/pty/0 from planet and eating the character entry. 

Closing.
