### ISSUE TITLE
[BUG] NFS unsupported in Planet container in Gravity 7.x

### ISSUE THREAD

**Issue by tosih** [gravitational/gravity#1718]
**Describe the bug**

It seems that `nfs-kernel-server` is not available in the planet container anymore. This causes all NFS mounts to fail on new Gravity 7.0.7 clusters. The NFS mounts work fine outside of the planet container, but are not supported inside the container, where they are used by pods.

**To Reproduce**

```
[root@ip-10-218-6-141 ~]# gravity exec mount -t nfs -o hard,nfsvers=3,sync 4.4.4.4:/export/exchange/anypoint-vcs poop/
mount.nfs: Protocol not supported
```
```
[root@ip-10-218-6-141 ~]# gravity exec apt install -y nfs-kernel-server
...
[root@ip-10-218-6-141 ~]# gravity exec mount -t nfs -o hard,nfsvers=3,sync 4.4.4.4:/export/exchange/anypoint-vcs poop/
[root@ip-10-218-6-141 ~]#
```
Now the mount works.

**Expected behavior**

The previous version of Gravity supported all types of NFS mounts.

**Logs**

See above.

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Centos 7.7
 - Gravity [e.g. 5.5.4]: Gravity 7.0.7
 - Platform [e.g. Vmware, AWS]: AWS

**Additional context**

**Comment by r0mant** [comment]
Released in [7.0.10](https://gravitational.com/gravity/docs/changelog/#7010-june-23rd-2020).
