### ISSUE TITLE
Make sure 7.0 is CNCF conformant

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1734]
## Description

We should execute CNCF certification suite and make sure Gravity 7.0 complies with it.

## Success

- [ ] Gravity 7.0 passes CNCF conformance suite and added to CNCF certified K8s list.

**Comment by knisbet** [comment]
```
kevin-7-conformance:/$ ./sonobuoy status
         PLUGIN     STATUS   RESULT   COUNT
            e2e   complete   passed       1
   systemd-logs   complete   passed       2

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```

```
{"msg":"Test Suite completed","total":280,"completed":280,"skipped":4563,"failed":0}

Ran 280 of 4843 Specs in 4601.783 seconds
SUCCESS! -- 280 Passed | 0 Failed | 0 Pending | 4563 Skipped
PASS

Ginkgo ran 1 suite in 1h16m43.399647002s
Test Suite Passed
```

This is a normal passing result. 

Reproduction steps are as per CNCF self certification described here: https://github.com/cncf/k8s-conformance/tree/master/v1.17/gravity

**Comment by helgi** [comment]
Is this baked into robotest?

**Comment by wadells** [comment]
> Is this baked into robotest?

No.  Nor are we tracking a backlog issue to do so (yet).  Though looking at https://github.com/cncf/k8s-conformance/tree/master/v1.17/gravity, it doesn't seem unreasonable.
