### ISSUE TITLE
Metrics satellite_etcd_leader and satellite_etcd_health show unexpected values

### ISSUE THREAD

**Issue by aocheretnoy** [gravitational/gravity#1759]
**Describe the bug**

There is a cluster with N nodes, 3 master and K workers. When I execute the next Prometheus query
count(satellite_etcd_leader) I got N.
For  sum(satellite_etcd_leader) I got X (X < N)
Which means we have N metrics with value 1 and others with value zero. It makes no sense to me, because I assume that only the master should show 1, so sum(satellite_etcd_leader) should be 3.
The satellite_etcd_health has also unexpected behaviour.

**To Reproduce**

1. Open prometheus
2. Execute the next requests: count(satellite_etcd_leader), satellite_etcd_health

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]:
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by r0mant** [comment]
@aocheretnoy @UnderGreen Has this been resolved? Can we close this now?
