### ISSUE TITLE
[Test Plan 7.0 LTS] Standalone Cluster

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1820]
# Standalone Cluster

### CLI Mode

- [x] Install Telekube cluster image in standalone CLI mode.
  - [x] Verify can create [local user](https://gravitational.com/gravity/docs/ver/6.x/config/#example-provisioning-a-cluster-admin-user), for example:
```yaml
kind: user
version: v2
metadata:
  name: admin@example.com
spec:
  type: admin
  roles: ["@teleadmin"]
  password: qwe123
```
  - [x] Verify can log into local cluster UI using the user created above.
  - [x] Verify can invite user to cluster using CLI.
    - [x] Create a user invite: `gravity users add test@example.com --roles=@teleadmin`.
    - [x] Open the generated link and signup.
    - [x] Verify can login with the created user.
  - [x] Verify can reset cluster user password using CLI.
    - [x] Request a user reset: `gravity users reset test@example.com`.
    - [x] Open the generated link and reset the password.
    - [x] Verify can login with the new password.
  - [x] Verify can join a node using CLI (`gravity join`).
  - [x] Verify can remove a node using CLI (`gravity leave`).

### UI Mode

- [x] Install Telekube cluster image in standalone UI wizard mode.
  - [x] Verify can complete bandwagon through wizard UI.
  - [x] Verify can log into local cluster UI with the user created in bandwagon.

**Comment by eldios** [comment]
when installing via CLI, the first user that logs in is prompted by the bandwagon "final setup step" that requires you to create the "first user", even if that is already present.

Can we make the user creation step optional?

**Comment by eldios** [comment]
when I create the user via bandwagon through web UI installation the created user gets automatically assigned the email `wizard@gravitational.io` even though I used the username `test` ... which is a bit confusing

**Comment by eldios** [comment]
known issue (I think):
if you're still logged in through the installation UI, which usually happens right after you finished installing, if you log out it will ask you for the 2FA in addition to username and password EVEN if 2FA is not configued.

This also confirms the point above about differentiating the Installation UI from the regular Web UI.
