### ISSUE TITLE
[Test Plan 7.0 LTS] Application Catalog

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1829]
# Application Catalog

This section covers the application catalog features. It requires a Hub.

### Building & Publishing

- [x] Build application images from the sample Helm charts in `assets/charts`.
```bash
$ tele build assets/charts/alpine-0.1.0
$ tele build assets/charts/alpine-0.2.0
```

- [x] Log into the Hub.
```bash
$ tsh login --proxy=example.gravitational.io:32009
```

- [x] Push the built application image into the Hub.
```bash
$ tele push alpine-0.1.0.tar
```

- [x] Make sure the application is shown in the image list.
```bash
$ tele ls
```

- [x] Verify the application image tarball can be downloaded from the Hub.
```bash
$ tele pull alpine:0.1.0
```

- [x] Verify Helm chart can be searched for and downloaded from the Hub.
```bash
$ helm search alpine
$ helm fetch example.gravitational.io/alpine --version 0.1.0
```

- [x] Verify one of the application's Docker images can be pulled from the Hub.
```bash
$ docker pull example.gravitational.io:32009/alpine:3.3
```

### Discovery

- [x] Install a cluster.

- [x] Connect the cluster to a Hub using [Trusted Cluster](https://gravitational.com/gravity/docs/config/#trusted-clusters-enterprise) resource.

- [x] Verify the application can be searched for in the connected Hub.
```bash
$ gravity app search --all
$ gravity app search alpine --all
```

### Lifecycle

- [x] Transfer both built application images (`alpine-0.1.0.tar`, `alpine-0.2.0.tar`) onto the cluster node.

- [x] Install the application.
```bash
$ gravity app install alpine-0.1.0.tar
```

- [x] Verify an application instance has been deployed.
```bash
$ gravity app ls
$ kubectl get pods
```

- [x] Install the application directly from the Hub.
```bash
$ gravity app install <hub-name>/alpine:0.1.0
```

- [x] Verify there are now 2 instances of the application running.
```bash
$ gravity app ls
$ kubectl get pods
```

- [x] Upgrade one of the deployed application.
```bash
$ gravity app upgrade <release-name> alpine-0.2.0.tar
```

- [x] Verify the application has been upgraded.
```bash
$ gravity app ls
```

- [x] Rollback the upgraded application.
```bash
$ gravity app rollback <release-name> 1
```

- [x] Verify the application has been rolled back.
```bash
$ gravity app ls
```

**Comment by bernardjkim** [comment]
Was unable to verify docker image pull. 
Using gravity hub 7.0.0.
Docker version 19.03.6.
> Verify one of the application's Docker images can be pulled from the Hub.
```
$ docker pull hub.gravitational.io:32009/alpine:3.3
Error response from daemon: Get https://hub.gravitational.io:32009/v2/alpine/manifests/3.3: no basic auth credentials
```

**Comment by UnderGreen** [comment]
@bernardjkim did you follow instructions from tsh login:
```
The server ci-ops.gravitational.io:443 provides Docker registry support but tsh was unable to configure your local Docker client due to insufficient permissions.

To configure your local Docker client tsh needs to symlink obtained certificates to /etc/docker/certs.d.
See https://docs.docker.com/engine/security/certificates/ for details.

If you'd like to configure your local Docker client, please create the following directory and make sure tsh has write permissions for it, for example:

  sudo mkdir -p /etc/docker/certs.d/hub.example.com:443 && sudo chown -R username /etc/docker/certs.d/hub.example.com:443
```

**Comment by UnderGreen** [comment]
Gravity docs, by the way, are inconsistent. Hub page has examples with `tsh login`, but application catalog page has `tele login`. With `tele login` there is no support for helm operations.

**Comment by bernardjkim** [comment]
Ah, thanks @UnderGreen. I totally missed that :sweat_smile:.  Was able to pull images fine after that step.
