### ISSUE TITLE
[BUG] containerd-shim hangs

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1842]
**Describe the bug**

A customer is using wormhole, 3-master cluster. After rebooting one of masters, overlay checker starts reporting issues with 2 other masters experiencing overlay issues with the rebooted master (node-2):

```
Masters:
* node-1 / 10.100.1.1 / worker
Status: healthy
[!] overlay packet loss for node 10.100.1.2 is higher than the allowed threshold of 20% (current packet loss at 100%)
Remote access: online
* node-2 / 10.100.1.2 / worker
Status: healthy
[!] overlay packet loss for node 10.100.1.1 is higher than the allowed threshold of 20% (current packet loss at 100%)
[!] overlay packet loss for node 10.100.1.3 is higher than the allowed threshold of 20% (current packet loss at 100%)
Remote access: online
* node-3 / 10.100.1.3 / worker
Status: healthy
[!] overlay packet loss for node 10.100.1.2 is higher than the allowed threshold of 20% (current packet loss at 100%)
Remote access: online
```

Looking in wormhole logs on node-2, it shows errors communicating with apiserver.

After wormhole pod restart, it comes up fine and the cluster recovers.

Another piece of information after some debugging:

It looks like in a general use-case wormhole does restart properly after reboot. There must be something else at play here. In the cluster where this was observed, there was a wormhole pod on the rebooted node, but no wormhole process somehow - so even "kubectl delete" had to be invoked with force flag. Maybe Kubernetes somehow "lost track" of the process/container after reboot, and so didn't start new wormhole pod at all?

**To Reproduce**

**Expected behavior**

Wormhole should start fine after reboot even if apiserver is momentarily unavailable, by retrying its calls to apiserver.

**Logs**

[wormhole-logs.txt](https://github.com/gravitational/gravity/files/4886063/wormhole-logs.txt)
[wormhole-logs-prev.txt](https://github.com/gravitational/gravity/files/4886064/wormhole-logs-prev.txt)

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 6.1
 - Platform [e.g. Vmware, AWS]:

**Comment by knisbet** [comment]
> Wormhole should start fine after reboot even if apiserver is momentarily unavailable, by retrying its calls to apiserver.

I'm not sure this really helps here. If there aren't available resources, such as the apiserver being unavailable, it's just as safe to crash the controller, and wait for it to be rescheduled. This allows the process to start on completely clean state, than to try and implement any specialized recovery, which adds it's own complexity.

**Comment by r0mant** [comment]
@knisbet Yes, I figured as much after inspecting wormhole code a bit more. I originally thought it just fails to reach apiserver with a really short retry limit and then never retries, but then saw that it actually crashes so it can be rescheduled, which is fine.

The actual problem like I mentioned is that wormhole doesn't actually appear to be running on the node at all, yet the pod shows "running", with the apiserver errors in the logs as the attached logs show.

**Comment by knisbet** [comment]
So investigating this with a customer today, yes it appears to be that container processes are able to exit, but docker/containerd still see the containers as running, so nothing tries to restart them. Investigating the containerd bug tracker suggests that a number of hangs / dead locks have been fixed in subsequent versions of containerd, but I wasn't able to collect stack traces from the shim to definitively link the hang seen by the customer to one of the known issues.

For now I've gone through and bumped containerd on 6.1 and docker on 7.0/master to try and avoid this problem.

Additional Info:
    - https://github.com/containerd/containerd/pull/3561
    - https://github.com/containerd/containerd/pull/3540
    - https://github.com/containerd/containerd/issues/3125
    - https://github.com/containerd/containerd/issues/3177
    - https://github.com/containerd/containerd/issues/3572#issuecomment-528293369

**Comment by knisbet** [comment]
Just leaving a note in the public ticket. 

It appears for customer T this fix has been ineffective, and we're re-investigating the problem. Currently trying to validate whether containerd-shim received the SIGCHLD event at all, and whether on these particular hosts the exit event is lost on every container exit or only selectively.

**Comment by ip6li** [comment]
Same problem with containerd version
containerd github.com/containerd/containerd v1.4.0.m 09814d48d50816305a8e6c1a4ae3e2bcc4ba725a.m
