### ISSUE TITLE
[BUG] gravity gc does not collect stale packages in /var/lib/gravity/site/packages/

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#1850]
**Describe the bug**
Disk utilitization in /var/lib/gravity/site/packages/ does not notably drop after running `gravity gc` as described in our [test plan](https://github.com/gravitational/gravity/blob/d4b3c67b2c8f785883fb1581c36e5ab435a6f71f/docs/7.x/testplan.md#collecting-garbage)

Before gc:

```
6.7G    /var/lib/gravity/local/packages
6.3G    /var/lib/gravity/site/packages
```
After gc:
```
2.7G    /var/lib/gravity/local/packages
6.3G    /var/lib/gravity/site/packages
```

```
$ ls /var/lib/gravity/site/packages/blobs/
027  0b2  106  15d  168  1d5  382  41d  447  526  560  571  61d  669  711  744  77b  7dd  883  8ea  985  a23  b26  c00  c65  cdb  e2c  ee8  f17
07f  0fa  119  166  1d4  32f  3eb  429  50f  53e  56e  5f3  621  6c2  739  775  7d3  7e7  8ce  901  9ce  a8b  b46  c5e  c87  d21  ee6  ee9  f94
$ ls /var/lib/gravity/local/packages/blobs/
07f  0b2  32f  382  429  447  560  61d  669  6aa  6c2  711  77b  7d3  8ce  985  9ce  a8b  b26  b46  c5e  c65  c87  cdb  e2c  ee8
```

**To Reproduce**
Follow the steps of the [garbage collection test plan](https://github.com/gravitational/gravity/blob/d4b3c67b2c8f785883fb1581c36e5ab435a6f71f/docs/7.x/testplan.md#collecting-garbage) using gravity OSS 6.1.29 as the starting version and 7.0.11 as the upgrade version/version under test.

**Expected behavior**
I expect (or rather, our test plan expects) that the disk utilitization of `/var/lib/gravity/site/packages/` will notably drop when `gravity gc` is run to prune packages after an upgrade .

**Logs**
None yet.  I can repro the scenario to gather some if particulars are needed.

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: Suse 12
 - Gravity [e.g. 5.5.4]: 6.1.29, 7.0.11
 - Platform [e.g. Vmware, AWS]: GCP

**Additional context**
I do not know if this is a regression yet, though the test plan seems to imply that it is.

Caught while testing #1823

**Comment by wadells** [comment]
There is record of @r0mant successfully completing the GC part of the test plan prior to the release of 7.0 in #1140. Thus I'm going to assume this is a regression since that point unless we gather evidence otherwise.

**Comment by ulysseskan** [comment]
Had similar happen with customer on 5.5.38 today.  Cluster was in a degraded state with multiple master nodes low on disk space.  gc operation failed to remove a bunch of old packages from each of the nodes.

Here's what we did to resolve:
* Customer restarted gravity-site (not sure if this made anything better or worse)
* kill/restart teleport on each node (to allow gravity agent to deploy without errors)
* gravity agent deploy
* gravity plan resume on gc operation

Also, Sergei has seen gc fail to clean up old packages on both 5.5.38 and 5.5.57.
