### ISSUE TITLE
Wizard installer ignores --set and --values flags

### ISSUE THREAD

**Issue by denniswebb** [gravitational/gravity#1901]
### Description

**What happened**:
I tried to install both with `./gravity install --wizard --set key=value` and with `./install --set key=value` so the installer would create `/var/lib/gravity/helm/values.yaml` for use during the install hook.

If I just do `./gravity install --set key=value` not using the wizard, the file is created as expected.

**What you expected to happen**:
`/var/lib/gravity/helm/values.yaml` should've been created with the contents `key: value`

**How to reproduce it (as minimally and precisely as possible)**:
Start a wizard install using the commands above.

### Environment

 - Gravity version [e.g. 7.0.11]: 4.0.13
 - OS [e.g. Redhat 7.4]: Ubuntu 18
 - Platform [e.g. Vmware, AWS]: AWS (generic profile though)

**Browser environment**

- Browser Version (for UI-related issues): Firefox
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

**Comment by stevenGravy** [comment]
The `--config` parameters for additional resource creation is also ignored.
