### ISSUE TITLE
Implement a new test cluster image for Robotest

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1908]
### Problem

Currently, Robotest uses our base [telekube](https://github.com/gravitational/gravity/tree/master/assets/telekube) image to exercise tests. The problem with this approach is that we cannot extend this base image with additional scenarios, to keep it "vanilla".

### Solution

Instead of testing with base image, we should build another application that will be used specifically by Robotest to exercise all sorts of test scenarios and which we will be constantly iterating on and extending with new features and use-cases.

Let's call this new test cluster image `robotest` and place it under [assets](https://github.com/gravitational/gravity/tree/master/assets) in this repo, alongside other images there. We can base it off of `telekube` and iterate on it.

### Success

We will consider our first step on the path to a feature-rich Robotest application a success when the following is completed:

- [x] There's a cluster image called `robotest` under the [assets](https://github.com/gravitational/gravity/tree/master/assets) directory.
- [x] The `robotest` cluster image has the following properties (see [Image Manifest](https://gravitational.com/gravity/docs/pack/#image-manifest) for details on these):
  - [x] It defines multiple node profiles and different flavors, can base it off of telekube app.
    - [x] Similar to telekube app, there should be an "auto" profile (that auto-selects the role), "master" and "node".
    - [x] There should be a single-node flavor, an HA flavor (say, with 3 and 6 masters), and a flavor that contains regular nodes (say, 1 master + 1 node and 3 masters + 3 nodes).
  - [x] It contains a simple Helm chart. For the first iteration, something simple like alpine/nginx will work.
  - [x] It defines **all** hooks that are on the "execution path" of current Robotest scenarios: install, postInstall, preUpdate, update, postUpdate, status, preNodeAdd, postNodeAdd, preNodeRemove, postNodeRemove, etc. (check what else).
  - [x] Node profiles specify volume mounts requirements with custom uid/gid.
  - [x] It enables additional features like OpenEBS and nginx ingress controller.
- [x] Robotest uses this `robotest` cluster image to exercise all test suites except upgrade (upgrade tracked in #1915)

### Time estimate

Best case scenario: 5 days.
Worst case scenario: 10 days.

**Comment by wadells** [comment]
>  Robotest uses this robotest cluster image to exercise all test suites.

I'd like to amend this to exclude upgrade from the initial work.  Upgrade requires a robotest.tar for all gravity versions upgraded to/from which is something significantly new for our build system and requires further design to do conscientiously.  I've filed https://github.com/gravitational/gravity/issues/1915 to track the further work.

**Comment by r0mant** [comment]
@wadells Sounds good.

**Comment by a-palchikov** [comment]
Having a single image will still be insufficient to test on/off scenarios. Something like the ability to override(all) values from the manifest at install/upgrade is necessary.

**Comment by wadells** [comment]
Work in progress here: https://github.com/gravitational/gravity/compare/master...wadells:robotest-image?expand=1

**Comment by a-palchikov** [comment]
Also the new test should exercise builds with alternative planet container images.
