### ISSUE TITLE
Implement support for NFS provisioner in robotest cluster image

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1909]
### Problem

Customers have complained in the past that NFS provisioning failed when upgrading between the versions due to a regression with missing package from planet: https://github.com/gravitational/planet/pull/687.

### Solution

We should enhance our Robotest test cluster image to deploy a NFS provisioner (so everything is contained within the cluster), and update the application to mount an NFS share.

NFS provisioner Helm chart: https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner
https://github.com/kubernetes-incubator/external-storage/tree/master/nfs
https://medium.com/@myte/kubernetes-nfs-and-dynamic-nfs-provisioning-97e2afb8b4a9

### Success

- [ ] `robotest` cluster image deploys an NFS provisioner Helm chart alongside other charts.
  - [ ] Optionally, it can be made optional by using Helm values so it's not installed in every test.
- [ ] One of `robotest` cluster image applications (charts) requests an NFS persistent volume.
- [ ] Robotest verifies that the pod was created and NFS share was mounted correctly.

### Timeline

Best case: 7 days
Worst case: 14 days

**Comment by tosih** [comment]
This should work well since we can test both NFS and StorageClass (we can mount an ebs volume) with this chart. We would need to add this:
```apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate```

**Comment by wadells** [comment]
During testing: make sure we try this against a broken gravity version (7.0.9) and it fails.
