### ISSUE TITLE
Allow a configurable robotest image

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#1923]
### Feature Request
Expand robotest testing to include on/off testing for various elements of the Gravity application manifest that are baked into the robotest image (e.g. OpenEBS, Ingress)

### Motivation
This was requested by @a-palchikov here:

https://github.com/gravitational/gravity/issues/1908#issuecomment-663440933

> Having a single image will still be insufficient to test on/off scenarios. Something like the ability to override(all) values from the manifest at install/upgrade is necessary.

### Who's it for?
Gravity Developers

**Comment by wadells** [comment]
@a-palchikov: Can you give me an example of a specific regression issue or two where a customized image would have helped catch the issue -- or we need to test both the on and off case?

I want to weigh the cost-benifit of thi -- it could dramatically increase the dimensional of our automated testing.

**Comment by a-palchikov** [comment]
I meant this as a way to test additional build/install paths when the system container image is completely replaced. See my other [comment](https://github.com/gravitational/gravity/issues/1925#issuecomment-665542539)

**Comment by wadells** [comment]
> I meant this as a way to test additional build/install paths when the system container image is completely replaced. See my other [comment](https://github.com/gravitational/gravity/issues/1925#issuecomment-665542539)

Is this something you think we should do as an automated test:
* on every PR
* on nightly builds on master?
* as one-off testing not integrated with CI (e.g. using robotest to aid manual testing or execution of a test plan)

I see this as a potentially very high cost ask given number of dimensions it would add to any CI based test matrix (PR or Nightly) which means it looks low ROI.  If it is for one-off testing with robotest, that isn't a use case the tool presently targets -- though it is certainly a laudable goal.

Please let me know if I'm misinterpreting the request.

**Comment by a-palchikov** [comment]
We could start with a one-off. Ideally this would be tested automatically but I'm not sure how often and whether on each PR.
