### ISSUE TITLE
Add infrastructure to test alternative planet containers with Robotest

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#1925]
### Feature Request
In our documentation, we allow end users to specify a custom planet container when building cluster images: 

https://gravitational.com/gravity/docs/pack/#custom-system-container

We should test building an image with a custom container.

### Motivation
This was requested by @a-palchikov here:

https://github.com/gravitational/gravity/issues/1908#issuecomment-665098144

> Also the new test should exercise builds with alternative planet container images.

### Who's it for?
Gravity developers.

**Comment by wadells** [comment]
@a-palchikov: I'm not sure I understand this request.  What is the use case?  E.g. Are you looking for automated testing of a particular scenario/regression?  Or is this for one-off testing?

Presently, if we override `PLANET_TAG` (by manually editing the Makefile), and produce a custom telekube.tar, robotest will use that tar in its runs.  This seems like it would meet needs for one-off testing.

I don't understand why we'd want to automatically test a custom planet image in e.g. PR builds or nightly builds.

**Comment by a-palchikov** [comment]
What I'm referring to with this is completely replacing the planet container (or customizing it for specific node profile) as described [here](https://gravitational.com/gravity/docs/pack/#custom-system-container). As an example - the current 7.0.x is broken w.r.t this - e.g. an installer that replaces the default system container image will not install. I stumbled on it by chance and it's a regression.

**Comment by wadells** [comment]
> As an example - the current 7.0.x is broken w.r.t this - e.g. an installer that replaces the default system container image will not install. I stumbled on it by chance and it's a regression.

Do we have an issue tracking this regression and its impact/priority?  I didn't find anything when I checked here:

https://github.com/gravitational/gravity/issues?q=is%3Aissue+planet+label%3Aregression

Of particular interest to this discussion, is this a regression users are hitting?  I'm looking to determine relative priority and also maybe a real world use case -- such that any custom planet image I implement for test purposes is less contrived.

**Comment by wadells** [comment]
As an intermediate goal, it'd be great to add a custom planet container to our manual test plan before the our run of the plan.

**Comment by a-palchikov** [comment]
Yes, I should've created the issue when I stumbled on it - will do now.

**Comment by wadells** [comment]
An important customer saw a regression in the functionality this would test: https://github.com/gravitational/gravity/issues/2125
