### ISSUE TITLE
Installation fails on Waiting for kubernetes API to start:cannot resolve non-cluster local address

### ISSUE THREAD

**Issue by rtpro** [gravitational/gravity#195]
Hi, 

I'm trying to install Gravity on CentOS 7.2. The installation procedure fails after a few minutes of 
Tue Jan 15 17:28:54 UTC [INFO]  Waiting for kubernetes API to start: Get https://leader.telekube.local:6443/api/v1/componentstatuses/scheduler: cannot resolve non-cluster local address
And then fails 
Phase execution failed: context deadline exceeded.

Not sure how to debug, find docker/Kuberentes logs or connect to docker daemon.

**Comment by klizhentas** [comment]
also, feel free to join our [Community Slack Channel](https://join.slack.com/t/grv8/shared_invite/enQtNTEwMTU2NjQ2NzU2LWIzYTM1ZDcyNWFhMzZhNDJhN2IyOWMwZDA4NDA4MmE2MjgzYWNiYmY1NjcxYjA3M2RmOTQ1ZjRkOTAwODE1NDY) where we will try to help you on the best effort basis! Thanks for giving Gravity a try!

**Comment by rtpro** [comment]
Thanks @klizhentas , i was looking for ~~planet enter~~
