### ISSUE TITLE
Gravity should exclude output file from resources

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1953]
### Feature Request

When building a cluster image using `tele build`, Gravity considers everything in the same directory where `app.yaml` resides the application resources, and packages those inside the tarball. This leads to the following confusing behavior: if a user places the built installer in the same directory, it will be packaged as well during subsequent builds.

For example:

```
tele build app.yaml -o installer.tar
```

In the above case, `installer.tar` will be placed in the same directory as `app.yaml`. Then, next `tele build` will package that giant installer file among application resources as well.

Instead, `tele build` can be smarter and skip the file if, say, it matches the output file name. So in the above case it can tell that "installer.tar" is the output and if it resides in the same directory, it should be skipped during build.

**Comment by dorsany** [comment]
Hi @r0mant , one way to workaround this is maybe to add `--ignore` flag like in `gravity app import`

```
--ignore=IGNORE ...        ignore files matching this regular expression when searching for container references
```
so with this we will be able to ignore just `*.tar` files
