### ISSUE TITLE
Planet journal gravity report improvements

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#1978]
### Feature Request

There are a couple of issues with planet journal logs collected as a part of gravity report at the moment:

* Sometimes they are missing i.e. `planet-journal-export.log.gz` is just several bytes in size and can't be unzipped. This is likely happens because we're using host's "journalctl" to read logs from planet's journal and run into compatibility issues.
* The current format is very inconvenient as it has to be post-processed and viewed like a journal. Can we collect them as a regular text file?

### Success

- [ ] Planet journal logs are collected using planet's journalctl and are always present in the report.
- [x] In additional to binary journal format, planet logs are also present as a regular text file which can just be opened in text editor.

**Comment by a-palchikov** [comment]
Planet journals are always collected using the container's version of journalctl to keep tool compatibility. One of the recent issues was that the path to journalctl inside the container (or in genera, in image's rootfs) was changed and the journal capture command was failing to find the executable.
