### ISSUE TITLE
Unable to upgrade when using custom planet image

### ISSUE THREAD

**Issue by yonatankahana** [gravitational/gravity#1993]
### Description

**What happened**:
I created custom image of the planet because I want to delete the PodSecurityPolicy enforcement. I could `gravity install` it without any issue but I was unable to upgrade since this version with the error: "failed to ping Docker registry: Get https://leader.telekube.local:5000/v2/: dial tcp: lookup leader.telekube.local: no such host".
I released a version without the custom planet, reinstalled all the cluster and since then I was able to upgrade. but the version that comes with a custom planet is broken and upgrade is failing.

* when i try to ping to the registry from `gravity shell`, the dns resolves and I have ping.
* the planet version not changed between the versions
* it was nicer to have a way to disable PSP for easier development.

### **What you expected to happen**:
The upgrade should complete successfully.

#### Dockerfile for custom planet:
```dockerfile
FROM quay.io/gravitational/planet:7.0.36-11709
RUN sed -i 's/PodSecurityPolicy\,//g' /lib/systemd/system/kube-apiserver.service
```

#### app.yaml node configuration
```yaml
nodeProfiles:
  - name: general
    systemOptions:
      baseImage: "myserver.domain.local:5000/repo/custom-planet:0.0.4"
```

1. Install the cluster image with resourceVersion 0.0.1 with the custom planet image
2. Bump the clusters resourceVersion to 0.0.2, build the image again
3. Try to upgrade the installed cluster to 0.0.2 

### Environment

 - Gravity version: 7.0.13 (planet: 7.0.36-11709)
 - OS: Ubuntu 18.04
 - Platform: qemu-kvm

**Relevant Debug Logs**
#### Upgrade logs
```
username@hostname:~/gravity# ./upgrade
Mon Aug 10 13:24:41 UTC Importing application myapp v0.0.2
Mon Aug 10 13:24:41 UTC Application already exists in local cluster
Mon Aug 10 13:24:41 UTC Synchronizing application with Docker registry leader.telekube.local:5000
[ERROR]: failed to connect to registry at "leader.telekube.local:5000"
        failed to ping Docker registry: Get https://leader.telekube.local:5000/v2/: dial tcp: lookup leader.telekube.local: no such host
                Get https://leader.telekube.local:5000/v2/: dial tcp: lookup leader.telekube.local: no such host
```

**Comment by a-palchikov** [comment]
`no such host` in this case means the coredns running inside the container is not properly resolving the address.
How big is the cluster? And let me know whether you can resolve `leader.telekube.local` with `nslookup leader.telekube.local 127.0.0.2` and whether the coredns is running (i.e. listening on `127.0.0.2:53`)?

**Comment by yonatankahana** [comment]
> How big is the cluster?

Single machine.


> resolve leader.telekube.local with nslookup leader.telekube.local 127.0.0.2

from the host itself:
```shell
$ username@hostname:~/gravity# nslookup leader.telekube.local 127.0.0.2
Server:         127.0.0.2
Address:        127.0.0.2#53

Name:   leader.telekube.local
Address: 192.168.103.10
** server can't find leader.telekube.local: NXDOMAIN
```

from `gravity shell`:
```shell
$ gravityplayground:/$ nslookup leader.telekube.local 127.0.0.2
Server:         127.0.0.2
Address:        127.0.0.2#53

Name:   leader.telekube.local
Address: 192.168.103.10
```

> whether the coredns is running

from the host itself:
```shell
$ username@hostname:~/gravity# netstat -plnt | grep ':53'
tcp        0      0 127.0.0.2:53            0.0.0.0:*               LISTEN      22317/coredns
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      640/systemd-resolve
```

from `gravity shell`:
```shell
$ gravityplayground:/$ netstat -plnt | grep ':53'
tcp        0      0 127.0.0.2:53            0.0.0.0:*               LISTEN      118/coredns
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
```

**Comment by a-palchikov** [comment]
I think I found a suspect code path but need to verify whether it is actually taken in this case. Would be able to share the output of `gravity package list gravitational.io`?

**Comment by yonatankahana** [comment]
@a-palchikov Sure:
```shell
$ username@hostname:~/gravity# gravity package list gravitational.io

[gravitational.io]
------------------

* gravitational.io/myserver.domain.local:5000/repo/custom-planet:0.0.4 521MB installed:installed,purpose:runtime
* gravitational.io/bandwagon:6.0.1 76MB
* gravitational.io/dns-app:0.4.1 64MB
* gravitational.io/fio:3.15.0 6.9MB
* gravitational.io/gravity:7.0.13 109MB installed:installed
* gravitational.io/kubernetes:7.0.13 5.6MB
* gravitational.io/logging-app:6.0.5 127MB
* gravitational.io/monitoring-app:7.0.2 346MB
* gravitational.io/planet:7.0.36-11709 515MB purpose:runtime
* gravitational.io/rbac-app:7.0.13 5.6MB
* gravitational.io/site:7.0.13 84MB
* gravitational.io/myproduct:7.1.40 3.3GB
* gravitational.io/storage-app:0.0.3 1.0GB
* gravitational.io/teleport:3.2.14 33MB installed:installed
* gravitational.io/tiller-app:7.0.1 34MB
* gravitational.io/web-assets:7.0.13 4.9MB
```

**Comment by a-palchikov** [comment]
ok - exactly what I thought - thanks! This will be a quick fix.

**Comment by yonatankahana** [comment]
when testing this on 7.0.17, when trying to `gravity stop` the cluster it failed with 
```
[ERROR]: no installed package for gravitational.io/planet:0.0.0 found
```

**Comment by a-palchikov** [comment]
@yonatankahana this is another [issue](https://github.com/gravitational/gravity/issues/2026). I submitted a [PR](https://github.com/gravitational/gravity/pull/2191) for that one.

**Comment by yonatankahana** [comment]
this fault has been resolved.
