### ISSUE TITLE
kubectl go-template sample command fails with gravity kubectl wrapper

### ISSUE THREAD

**Issue by andrewtappert** [gravitational/gravity#201]
The sample command here fails when run on a gravity cluster:
https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/#list-containers-using-a-go-template-instead-of-jsonpath

$ kubectl get pods --all-namespaces -o go-template --template="{{range .items}}{{range .spec.containers}}{{.image}} {{end}}{{end}}"
error: a resource cannot be retrieved by name across all namespaces

It works if you enter the planet and invoke /usr/bin/kubectl directly, but not when use the kubectl wrapper script from within or outside the planet.

**Comment by a-palchikov** [comment]
Thanks for your bugreport - I was able to find the problem and will PR changes in a bit.

**Comment by a-palchikov** [comment]
Fixed in https://github.com/gravitational/planet/pull/369 for master.
