### ISSUE TITLE
Ensure etcd auto-compaction is enabled

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#2025]
### Feature Request
We should set `--auto-compaction-retention` flag for etcd. Currently, it appears that `AutoCompactionRetention` defaults to `0` if not set for all etcd versions. 

Link to etcd check on `AutoCompactionRetention` [here](https://github.com/etcd-io/etcd/blob/c60dabf2f30227852e725464193de6cb78829997/embed/etcd.go#L153).

### Motivation
Considering space quota is limited, it is good to clear out the keyspace history, which can be achieved through auto-compaction. Per customer feedback there have been many surfaced instances where db starts growing until it runs into the `mvcc: database space exceeded`

### Who's it for?
OSS User, Enterprise

**Comment by r0mant** [comment]
Was enabled in all branches, will be a part of next releases.
