### ISSUE TITLE
Upgrade K8s to 1.19 in 7.1 and master

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#2028]
### Feature Request

1.19 is about to be released, we need to upgrade to it in master and publish 7.1.0-alpha.

Success:

- [ ] We have released a stable 7.1 release that's based off of 7.0 with K8s 1.19.
- [ ] master has become 7.2 with K8s 1.19 as well.

**Comment by UnderGreen** [comment]
Tracking related PRs:
- [ ] [satellite](https://github.com/gravitational/satellite/pull/289)
- [ ] [rigging](https://github.com/gravitational/rigging/pull/92)
- [ ] [planet](https://github.com/gravitational/planet/pull/811)
- [ ] [logging-app](https://github.com/gravitational/logging-app/pull/76)
- [ ] [storage-app](https://github.com/gravitational/storage-app/pull/5)
- [ ] [bandwagon](https://github.com/gravitational/bandwagon/pull/33)
