### ISSUE TITLE
Serf cluster brain split

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#2100]
### Description

**What happened**:

If one of serf nodes is partitioned off of the rest of the cluster for too long (>24h), serf will eventually kick it out of the cluster and it will result in the cluster brain split situation when the node comes back.

For example, here's the situation observed on one of the clusters:

```bash
# on a controller
> serf members
192_168_0_1.c01  192.168.0.1:7496  alive  role=master,publicip=192.168.0.1

# on a worker
> serf members
192_168_0_2.w01  192.168.0.2:7496  alive  role=node,publicip=192.168.0.2
192_168_0_3.w02  192.168.0.3:7496  alive  role=node,publicip=192.168.0.3
```

Another issue is that in such a case `gravity status` shows "active" status yet the nodes are offline:

```
Cluster status: active
...
Cluster nodes:
  Masters:
    * c01 (192.168.0.1, controller_node)
      Status: healthy
  Nodes:
    * w02 (192.168.0.2)
      Status: offline
    * w01 (192.168.0.3)
      Status: offline
```

**What you expected to happen**:

- [ ] `gravity status` should display "degraded" in such situation.
- [x] Gravity should attempt to re-join missing serf member to the cluster automatically.

**How to reproduce**:

1. Install a 3-node cluster.
2. On one of the nodes execute `serf force-leave -prune <another-node>`.
3. Check `serf members` and `gravity status`.

### Environment

 - Gravity version [e.g. 7.0.11]: 5.5 and later

**Comment by helgi** [comment]
Time to ditch serf? ;)
