### ISSUE TITLE
WIzard installation broken

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#2134]
### Description

**What happened**:
Wizard installation is broken. When started, the installer fails with:
```
$ ./install
Thu Sep 17 15:26:23 UTC	Starting enterprise installer
[ERROR]: invalid pod subnet: 
	invalid CIDR address:
```

**What you expected to happen**:
Installation works.

### Environment

 - Gravity version [e.g. 7.0.11]: 6.1.33
 - OS [e.g. Redhat 7.4]:
 - Platform [e.g. Vmware, AWS]:

**Comment by aelkugia** [comment]
Marking as closed via #2135 and #2137
