### ISSUE TITLE
Re-check TLS versions and cipher-suites across the project.

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#2181]
We generally use Mozilla Modern has a reference for our internal communications as we generally control clients and servers (https://wiki.mozilla.org/Security/Server_Side_TLS) but we're behind and more in the intermediate range these days.

It's probably time to go through and update the configuration across all the gravity components.

We can also consider going to Ed25519 certificates because we control both clients and servers, but may need some thought.

**Comment by lenko-d** [comment]
The current etcd that we use doesn't support TLS v1.3 cipher suites. It fails to start with error:

```
unexpected TLS cipher suite
```

We will go with Mozilla intermediate compatibility until etcd implements support for v13 ciphers.

**Comment by lenko-d** [comment]
The current version of kube-apiserver that we use doesn't support TLS v13 suites. It fails to start with error:

```
kube-apiserver[16629]: Error: Cipher suite TLS_AES_128_GCM_SHA256 not supported or doesn't exist
```
The latest version of Kubernetes supports v13. We will go on with Mozilla intermediate compatibility until we upgrade k8s and after that we will upgrade the cipher suites as well.

**Comment by lenko-d** [comment]
Our current kubelet also doesn't support v13 Mozilla modern level ciphers:

```
kubelet[13373]: F1215 20:48:25.086905   13373 server.go:253] Cipher suite TLS_AES_128_GCM_SHA256 not supported or doesn't exist
```

**Comment by lenko-d** [comment]
Kube-scheduler:
```
kube-scheduler[13393]: Cipher suite TLS_AES_128_GCM_SHA256 not supported or doesn't exist
```

**Comment by lenko-d** [comment]
```
monitoring    kube-state-metrics-7975db7f8c-j6fs2                              1/3     CrashLoopBackOff   36         87m
```

Container: kube-rbac-proxy-main
```
main.go:233] Failed to convert TLS cipher suite name to ID: Cipher suite TLS_AES_128_GCM_SHA256 not supported or doesn't exist
```

**Comment by lenko-d** [comment]
Work on this story is postponed due to the version of Kubernetes that we use not supporting the new ciphers. We may revisit after we upgrade K8s to another version.
