### ISSUE TITLE
Gracefully remove node from cluster on AWS node termination

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#2200]
### Feature Request
Describe in as much detail as possible what feature you would like to see added and how it should work. 

### Motivation
Describe why we should work on this feature request.

### Who's it for?
OSS User, Enterprise

**Comment by helgi** [comment]
How different is this from https://github.com/gravitational/gravity/issues/942 ? 

Right now the SQS handles the removal and passes to `gravity remove`, eventually, it gets a bit janky atm due to how join/remove can't happen in parallel atm.

Curious of the scope here

**Comment by r0mant** [comment]
@helgi The use-case targeted here is when someone terminates the instance directly via AWS control panel so it doesn't go through ASG lifecycle hooks. Not sure yet if there's a way to tell this scenario from a regular node shutdown and launch shrink in this case, needs some research.
