### ISSUE TITLE
CRD on helm

### ISSUE THREAD

**Issue by sandromello** [gravitational/gravity#228]
I'm trying to add a CRD but `apiextensions.k8s.io/v1beta1` it's not recognized as a valid type when building my bundle: 

```bash
tele build -o bundle.tar appliance/gravity/resources/app.yaml
```

Ref: https://github.com/gravitational/gravity/blob/5.5.0-alpha.6/lib/app/resources/resourcefiles.go#L196

```
Will skip unrecognized object in Helm chart charts/kong: apiVersion=apiextensions.k8s.io/v1beta1, kind=CustomResourceDefinition
Will skip unrecognized object in Helm chart charts/kong: apiVersion=apiextensions.k8s.io/v1beta1, kind=CustomResourceDefinition
Will skip unrecognized object in Helm chart charts/kong: apiVersion=apiextensions.k8s.io/v1beta1, kind=CustomResourceDefinition
Will skip unrecognized object in Helm chart charts/kong: apiVersion=apiextensions.k8s.io/v1beta1, kind=CustomResourceDefinition
```

Is this intentional and there's another way of adding a CRD?

**Comment by a-palchikov** [comment]
The warning itself is intentional and is supposed to be harmless (i.e. it should be just ignored at this point) but there's also a bug that filters the unrecognized resources.
Thanks for reporting this - we'll have this fixed.

**Comment by a-palchikov** [comment]
Closed in https://github.com/gravitational/gravity/pull/229. 
And like I mentioned - the warning is there to point out that the resource has not been processed by the build operation (i.e. no docker image references were extracted).
