### ISSUE TITLE
Add ability to configure podCidr subnet length

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#2280]
### Feature Request

By default flannel provisions /24 subnets for each node. Some customers would like ability to override this, for example to request smaller subnets.

The Cluster Configuration resource should allow a `PodSubnetSize` field to specify the size of the subnet allocated to each host (default to 24):

```
// config.yaml
kind: ClusterConfiguration
version: v1
spec:
  global:
    podSubnetSize: "26"
```

With this Cluster Configuration defined, Gravity can be installed to use the specified Pod subnet size with:
```bash
$ sudo ./gravity install --config=config.yaml
```

Pod subnet size can also be reconfigured after installation by updating the Cluster Configuration resource:
```bash
$ sudo gravity resource create config.yaml
```

Configuration-wise, this property should make it into the flannel's config stored in etcd under `SubnetLen` key ( https://github.com/coreos/flannel/blob/master/Documentation/configuration.md), propagates same way as other variables are, via planet config and container-environment file.

Success criteria:

- [ ] Gravity install CLI provides the flag for overriding the default pod subnet size.
- [ ] The default property value is `24`.
- [ ] Make sure to validate the property:
  - [ ] That is has a reasonable max value so e.g. requesting /31 is not allowed.
  - [ ] Make sure it's not larger than the pod network CIDR range itself.
- [ ] Make sure the property is preserved during upgrades.

### Who's it for?
OSS User, Enterprise

**Comment by knisbet** [comment]
I think an alternate approach is to add this to the ClusterConfiguration resource and use ClusterConfiguration to tune the SubnetLen value passed to flannel.

**Comment by r0mant** [comment]
@knisbet Yeah, I think adding it to `ClusterConfiguration` resource might actually be a better approach. Feel free to update the ticket description. In that case, I think we'll also automatically support updating it on a deployed cluster unless there will be some issues when reconfiguring flannel one-by-one during the resource update.

**Comment by knisbet** [comment]
> @knisbet I think we'll also automatically support updating it on a deployed cluster unless there will be some issues when reconfiguring flannel one-by-one during the resource update.

We'll need to validate what actually happens. My suspicion is that if flannel say crashes and restarts our of sequence, the nodes could fight eachother a bit on what the value is, up until the rolling update is complete. I suspect also, that the leases won't change on any existing node, so we'll need to consider whether we should explicitly delete the leases, although the rolling restart might already handle that in however it handles podCidr changes.
