### ISSUE TITLE
Retrieving plan with operation ID does not always work

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/gravity#2309]
### Description

**What happened**:
Given multiple operations available in the backend, `gravity plan [display] --operation-id=<id>` might not display the correct operation.

**What you expected to happen**:
If an operation is selected with an ID, `gravity plan` correctly displays its details.

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
Start an operation after the installation (e.g. runtime environment update - does not have to run automatically, suffice that the operation and the plan are created).
Query the install operation with its ID.

 - Gravity version [e.g. 7.0.11]: 7.0.23

**Comment by tokiwong** [comment]
Also seen on Gravity version 7.0.30

**Comment by helgi** [comment]
Is `master` affected?

**Comment by a-palchikov** [comment]
No, but I'll backport.
