### ISSUE TITLE
Update "We are always hiring!" link

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#2378]
## Summary
In our README.md we link to https://gravitational.breezy.hr where we encourage candidates to apply.  However we switched to use Lever as our applicant tracking system: https://jobs.lever.co/gravitational

We should update the following line:
```
* Want to join our team to hack on Gravity? [We are always hiring!](https://gravitational.breezy.hr/)
```
to be:
```
* Want to join our team? [We are always hiring!](https://jobs.lever.co/gravitational)
```

## Note
I'm filing this as a easy first bug for a git workshop that I'm running.

**Comment by Siddharth1010** [comment]
@wadells Hey could you assign this to me?

**Comment by wadells** [comment]
Hi @Siddharth1010,

I filed this bug as an easy one to get started with for new git users in a Teleport training I'm running later today.  If I don't end up using it for that, I'd be glad to have you fix it.  Until I wrap that up that, I'd encourage you not to start on it, as I will likely delegate it to a student.

**Comment by Siddharth1010** [comment]
@wadells Okay, no worries :)

**Comment by wadells** [comment]
> @wadells Hey could you assign this to me?

We didn't end up using this ticket for the class.  Go for it!

**Comment by Siddharth1010** [comment]
@wadells I have made the change and created a PR. Let me know if I need to change anything :)
