### ISSUE TITLE
Update community url to goteleport.com

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#2379]
## Summary
The CONTRIBUTING.md file directs users to our community formus.   Travis recently updated the forum domain from community.gravitational.com to community.goteleport.com.

The following line should be changed from:
```
asking in the [community forum](https://community.gravitational.com/) first.

```
to 
```
asking in the [community forum](https://community.goteleport.com/) first.

```
https://github.com/gravitational/gravity/blob/7439c49928c7484525d6f5aa48de9acba740090e/CONTRIBUTING.md#filing-an-issue

## Note
I'm filing this as a easy first bug for a git workshop that I'm running.

**Comment by wadells** [comment]
@kafipayne: This would be a good ticket if you want to practice your git skills.

**Comment by 96RadhikaJadhav** [comment]
@wadells  Can I work on the issue?

**Comment by wadells** [comment]
> @wadells Can I work on the issue?

Hi @96RadhikaJadhav!  I've got this flagged for someone else at the moment -- as a git learning exercise.  Thanks for asking.
