### ISSUE TITLE
Ingress Error with app.yaml

### ISSUE THREAD

**Issue by sosukeinu** [gravitational/gravity#2463]
### Description

**What happened**:
I am currently testing a very minimal cluster image creation. I receive the following error after issuing `tele build app.yaml -f -v`

```bash
[ERROR]: could not parse the application manifest:
I[#] S[#] doesn't validate with "schema.json#"
  I[#] S[#/$ref] doesn't validate with "#/definitions/Manifest"
    I[#] S[#/definitions/Manifest/additionalProperties] additionalProperties "ingress" not allowed
```

**What you expected to happen**:

I expect the cluster image to be built. 

**How to reproduce it (as minimally and precisely as possible)**:

Create an `app.yaml` file that contains the following:

```yaml
apiVersion: cluster.gravitational.io/v2
kind: Cluster
metadata:
  name: Test
  resourceVersion: 0.0.1
  description: |
    My description
  author: me
baseImage: gravity:7.0.28
logo: file://logo.png
ingress:
  nginx:
    enabled: true
```
Then, issue `tele build app.yaml -f -v`.

### Environment

 - Gravity version [e.g. 7.0.11]: 7.0.28
 - OS [e.g. Redhat 7.4]: Ubuntu 18.04
 - Platform [e.g. Vmware, AWS]: Local

**Comment by ulysseskan** [comment]
Thanks for raising this.  Per https://goteleport.com/gravity/docs/changelog/ , ingress functionality was added in the 7.1 pre-release, not 7.0.28.

**Comment by sosukeinu** [comment]
> Thanks for raising this. Per https://goteleport.com/gravity/docs/changelog/ , ingress functionality was added in the 7.1 pre-release, not 7.0.28.

Thank you very much for this. How does one specify the baseimage to be used in the `app.yaml` for pre-release versions? I keep getting a baseimage not found. Thank you.

**Comment by sosukeinu** [comment]
I found the correct image using `tele ls --all` thank you for your time.
