### ISSUE TITLE
Use Custome CA and Certificates for Gravity clusters

### ISSUE THREAD

**Issue by Ahmadabed83** [gravitational/gravity#2510]
### Feature Request
Instead of having self-signed CA, that is created during the installation time, we need to have our own certificates and CA for all Gravity components

### Motivation
Security requirements are preventing us from using any self-signed certificates

### Who's it for?
OSS User, Enterprise

**Comment by a-palchikov** [comment]
This can be achieved with [tls key pair resource](https://goteleport.com/gravity/docs/config/#tls-key-pair) - does this work for your use-case?
