### ISSUE TITLE
tele build error "failed to export image layers"

### ISSUE THREAD

**Issue by wadells** [gravitational/gravity#2557]
### Description

**What happened**:

Users reported `tele build` failing on 8.0.0-beta.1 when it previously worked on 8.0.0-beta.0.

```
[2021-06-23T19:19:31.855Z] Wed Jun 23 19:19:31 UTC	Build finished in 4 seconds
[2021-06-23T19:19:31.855Z] [ERROR]: failed to export image layers
[2021-06-23T19:19:31.855Z] 	Error response from daemon: Get https://leader.telekube.local:5000/v2/: dial tcp: lookup leader.telekube.local: Temporary failure in name resolution
[2021-06-23T19:19:31.855Z]
```

**What you expected to happen**:

The same build succesfully created an installer tar with 8.0.0-beta.0.

### Environment

 - Tele version : 8.0.0-beta.1
 - OS :

**Comment by wadells** [comment]
@helgi: Can you add minimal public repro steps here?

**Comment by a-palchikov** [comment]
It looks like some (docker) image references might be pointing to `leader.telekube.local` (internal cluster registry) during the build? The `build` rewrites the image references to point to the internal registry before they're placed into the tarball but the original references should not reference the internal registry or these resources should not be looked at by `build`. This would break on both versions though.
Debug logs will help here (`tele build --debug`).

**Comment by wadells** [comment]
> It looks like some (docker) image references might be pointing to `leader.telekube.local` (internal cluster registry) during the build?

I found out that this happened during a re-pack of the opscenter tarball.  Apparently the workflow is something like:

* download opscenter.tar
* unpack the installer
* build a new tarball using an edited copy of the vendored app.yaml

Apparently this worked in builds prior to 8.0.0-beta.0.  It isn't a workflow that we test at Teleport.
