### ISSUE TITLE
Support for RHEL 8.4

### ISSUE THREAD

**Issue by federicoboerr** [gravitational/gravity#2563]
### Feature Request
Support for RHEL 8.4 in gravity 7.

### Motivation
Customers want to use the latest version of RHEL.

### Who's it for?
Everyone.

**Comment by wadells** [comment]
I've completed preliminary testing with RHEL/CentOS 8.4 (actually centos stream @ 8.4.2105) and everything looks fine.  I'll have final testing and docs update out in a bit.
