### ISSUE TITLE
Gravity release automation fails during publish task

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/gravity#2631]
### Description
Gravity release automation fails the `publish-oss` and `publish-enterprise` tasks.
See https://drone.teleport.dev/gravitational/gravity/395. 

A possible solution may be modify the `make build build-tsh release` on osx, and remove the requirement to clone teleport.e.

**Comment by wadells** [comment]
https://github.com/gravitational/ops/blob/52c81b80a5cae6029673154fec3f5052e4de30d4/xcloud/release-telekube-mac.yaml#L25 is one fix (missed from #2466).  There is another more nuanced issue where gravity `make build build-tsh release` eventually chains into `git submodule update --init --recursive` that fetches  teleport.e.

```
git submodule update --init --recursive
Submodule 'e' (git@github.com:gravitational/teleport.e.git) registered for path 'e'
Submodule 'webassets' (https://github.com/gravitational/webassets.git) registered for path 'webassets'
Cloning into '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.VP1Zatjt/src/github.com/gravitational/gravity/build/src/github.com/gravitational/teleport/e'...\nPermission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:gravitational/teleport.e.git' into submodule path '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.VP1Zatjt/src/github.com/gravitational/gravity/build/src/github.com/gravitational/teleport/e' failed
Failed to clone 'e'.
```

I haven't figured out where the code controlling that lives yet.
