### ISSUE TITLE
How to Ship a single container when a customer installed with the provided gravity tarball

### ISSUE THREAD

**Issue by pachalk** [gravitational/gravity#2722]
## Summary
I didn't find any documentation for shipping a single container to customers. Gravity will use tele command to build all the necessary things and bundle all the images into a tar folder. We can provide customers this tar to install our application using gravity install command but what if we want to ship a single container for that application which is installed with multiple containers. Is there any documentation process for this or any alternative solution for shipping a container for Airgapped network clients.

**Comment by wadells** [comment]
Hi pachalk,

Check out gravity's application catalog:

https://github.com/gravitational/gravity/blob/1857b92a9494fe9f997974217f2660d079e3dcf0/docs/9.x/catalog.md

That said, Gravitational is not actively developing Gravity any further.  [We're focusing on Teleport](https://goteleport.com/blog/gravitational-is-teleport/) now.

As such, I'd discourage you from using Gravity unless you plan to fork and support it yourself.

Let me know if you have further questions.
