### ISSUE TITLE
7.0.36 unable to mount volumes on Google Cloud

### ISSUE THREAD

**Issue by ulysseskan** [gravitational/gravity#2727]
### Description

**What happened**: Customer reported Gravity 6.x and 7.0.35 are able to mount volumes on Google Cloud, but 7.0.36 can't.  Mount fails with error similar to:

```
 Warning  FailedMount             3s         kubelet, a-test13cp-1  Unable to attach or mount volumes:
 unmounted volumes=[pg-persistent], unattached volumes=[pg-persistent default-token-xz8m8]:
 timed out waiting for the condition

  Warning  FailedMount             9m17s kubelet, a-test13cp-1  MountVolume.WaitForAttach failed for volume
"pg-persistent" : could not find attached GCE PD "test7036-kubernetes-disk".
Timeout waiting for mount paths to be created
```

This latter error is shown in the k8s code in [attacher.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gcepd/attacher.go#L278)

**What you expected to happen**:
Attach and mount the volume, ex.   AttachVolume.Attach succeeded for volume ... etc.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install gravity 7036 (one node is fine) on GCE VM ([extra GCE instructions](https://github.com/gravitational/gravity/blob/master/docs/7.x/installation.md#google-compute-engine)) `sudo ./gravity install --cloud-provider=gce --token=7036test`
2. Create a disk `gcloud compute disks create --size=20GB --zone=YOURGRAVITYCLUSTERREGION test7036-disk`
3. `sudo kubectl create -f pod.yaml` with the following pod.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - name: myfrontend
    image: nginx
    volumeMounts:
    - mountPath: /test-pd
      name: mypd
  volumes:
  - name: mypd
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName:  test7036-disk
      fsType: ext4
```

These same steps work fine on an installation of 7.0.35.

### Environment

 - Gravity version [e.g. 7.0.11]: 7.0.36
 - OS [e.g. Redhat 7.4]: Ubuntu 18.04.5 LTS
 - Platform [e.g. Vmware, AWS]: GCE

The major change in 7.0.36 was the newer golang version.  ([1.12.9 -> 1.17.5](https://go.dev/doc/devel/release#go1.17.minor))  Not sure how or if this is affecting mounts though.  Have not tested on AWS or other cloud providers so I don't know if the same problem exists there.  [gravity 7036 changelog](https://github.com/gravitational/gravity/blob/master/docs/9.x/changelog.md#7036-january-19-2022)

Customer also tried the GCE CSI driver and it reported the error a bit differently:
```
Warning  FailedMount             3m16s  kubelet, 10.0.0.73       MountVolume.MountDevice failed for volume
"pvc-184bb7 ..." : rpc error: code = Internal desc = Error when getting device path: rpc error: code = Internal desc
= error verifying GCE PD ("pvc-184bb732 ...") is attached: failed to find and re-link disk pvc-184bb732 ...
with udevadm after retrying for 3s: failed to trigger udevadm fix: udevadm --trigger requested to fix disk
pvc-184bb732- ... but no such disk was found
```
Similar GCE CSI driver error at: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/608

**Comment by bernardjkim** [comment]
Dynamic volume detection implemented in https://github.com/gravitational/planet/issues/88. Going to look through the code here to see if Go upgrade might have broken anything.

**Comment by bernardjkim** [comment]
After running the following command, the PD was able to be mounted.
```sh
$ mknod /dev/sdc b 8 32
```

I'm still reading up on on devices, but I think planet is probably failing around [here](https://github.com/gravitational/planet/blob/06eeabcebf601f5e98553bc0e0cbeb2120f0a190/tool/planet/devices.go#L56).

**Comment by bernardjkim** [comment]
Maybe a more relevant PR https://github.com/gravitational/planet/pull/281

**Comment by bernardjkim** [comment]
@wadells @ulysseskan 

I'm running out of ideas. From what I understand, this is how Planet handles dynamically creating devices:

Planet runs a [udev listener](https://github.com/gravitational/planet/blob/35fcba72388e649f47115ecf9a4766a83d4ea96f/tool/planet/udev.go#L35) listening for block device events. We can also use the `udevadm` tool to view the same events.
```
$ udevadm monitor --udev --subsystem-match=block --tag-match=systemd
...
UDEV  [453064.243708] add      /devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:17/0:0:17:0/block/sdc (block)
...
UDEV  [468731.700044] remove   /devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:28/0:0:28:0/block/sdc (block)
```

Whenever a block device is added, the Planet `device add` command is called to add a new device to the container. This invokes [mknod](https://github.com/gravitational/planet/blob/35fcba72388e649f47115ecf9a4766a83d4ea96f/tool/planet/devices.go#L63)  within the Planet container to create the node device file in the planet container
```
$ planet device add --data {"type":98,"path":"/dev/sdc","major":8,"minor":32,"permissions":"rwm","file_mode":25008,"uid":0,"gid":6,"allow":false}
```

Executing the `planet device add` command in Planet works just fine. So I think the problem is either in the udev listener not detecting the events, or in the way commands are executed in the Planet container.
