### ISSUE TITLE
tele build vendoring of sha256 references (invalid tag format)

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#273]
tele build vendoring of resources doesn't currently support image references pointed at a hash instead of a tag.

`quay.io/test@sha256:d237a12aa0cde42b539bcb5efc1118ba5e6ca1351b7493ed52bd574d181c5efd`

```
ERRO             "
ERROR REPORT:
Original Error: *docker.Error API error (500): {\"message\":\"invalid tag format\"}

Stack Trace:
	/gopath/src/github.com/gravitational/gravity/lib/app/service/docker.go:218 github.com/gravitational/gravity/lib/app/service.tagImageWithoutRegistry
	/gopath/src/github.com/gravitational/gravity/lib/app/service/vendor.go:272 github.com/gravitational/gravity/lib/app/service.(*vendorer).VendorDir.func1
	/gopath/src/github.com/gravitational/gravity/lib/run/run.go:85 github.com/gravitational/gravity/lib/run.(*Group).Go.func1
	/go/src/runtime/asm_amd64.s:2362 runtime.goexit
User Message:
" tele/main.go:23
[ERROR]: API error (500): {"message":"invalid tag format"}
```

**Comment by webvictim** [comment]
Same thing as https://github.com/gravitational/gravity.e/issues/3813

**Comment by dirien** [comment]
Can confirm this: working with gravity 7.x and ingress-chart

`        Pulling remote image k8s.gcr.io/ingress-nginx/controller:v0.35.0@sha256:fc4979d8b8443a831c9789b5155cded454cb7de737a8b727bc2ba0106d2eae8b
        Still embedding application container images (50 seconds elapsed)
        Using local image quay.io/gravitational/debian-tall:buster
        Still embedding application container images (1 minute elapsed)
Tue Sep  8 15:58:29 UTC Build finished in 1 minute 
[ERROR]: API error (500): {"message":"invalid tag format"}
`
