### ISSUE TITLE
`tele build -f` doesn't seem to overwrite

### ISSUE THREAD

**Issue by itay** [gravitational/gravity#379]
Despite being a documented flag, the option to overwrite the existing tar when doing `tele build` using either `tele build -f` or `tele build --overwrite` has no impact. From looking at the code it doesn't seem to be wired but I may just have missed it.

**Comment by r0mant** [comment]
Hi @itay!

The flag is actually being used here: https://github.com/gravitational/gravity/blob/5.5.8/lib/builder/build.go#L45.

What's the behavior you're seeing?

**Comment by itay** [comment]
I can't seem to reproduce this anymore (even though I did before I opened the ticket), so I'll close it. Sorry for the trouble!
