### ISSUE TITLE
Health Checks: gravity pods are running

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#391]
Related Issue (http_proxy installation related problems): https://github.com/gravitational/gravity.e/issues/3998

A customer encountered an issue where they tweaked docker settings to add http_proxy, which caused a side effect where requests for .local were being sent to the proxy which couldn't process them. This caused the internal gravity pods / pods distributed via the local registry to fail during pull.

This ticket is to look into adding satellite checks for failed/missing pods / internal cluster state, that can bubble forwards to the user / support engineer to indicate where problems with the cluster might be located.

**Comment by itay** [comment]
If it helps, I actually encountered this as well. It failed even earlier during installation, as it couldn’t resolve leader.telekube.local when it wanted to see if the Kubernetes API was available.

**Comment by knisbet** [comment]
Thanks. The issue with using http_proxy during installation is captured on our internal repo and has been observed a few times. Sorry it's not visible to the public. I opened this issue, more as an aid in troubleshooting the generalized issue, that if pods are failing for any reason, that we try and bubble this information up so it's easier to identify / notice these types of failures when doing remote support.

**Comment by itay** [comment]
No problem - just thought I’d add the specific issue we had run into.

**Comment by r0mant** [comment]
This was implemented in the form of a system pods checker in satellite.
