### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by twakes** [gravitational/gravity#444]
**Describe the bug**
Gravity is still using the old Telekube logo for its favicon

**To Reproduce**
Take a look at https://github.com/gravitational/gravity/tree/master/web/src/assets

**Expected behavior**
Should use new gravity logo for favicon

**Comment by alex-kovoy** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/7816406/61403023-64c04000-a8a2-11e9-92d1-40e392e9fc05.png)
