### ISSUE TITLE
Improved Audit log output.

### ISSUE THREAD

**Issue by benarent** [gravitational/gravity#496]
A ticket based on internal conversation. 

- [x] Be more explicit in audit message for when a customer adds a license. e.g. ` License for max nodes 4 has been generated`
- [x] Fix table sorting arrows
- [x] Change `Social User Login` to `SSO Login`

**Comment by alex-kovoy** [comment]
fixed by https://github.com/gravitational/gravity/commit/f50f0a8887c4f104a39a7cfe8221699dc40b7185 and https://github.com/gravitational/gravity/commit/d9f4cf9b6534937399c67c866bfee46cebdd4579
