### ISSUE TITLE
[BUG] SourceDestinationCheck=false missing on AWS node

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#503]
**Describe the bug**

A node was discovered in an AWS integrations cluster that had SourceDestinationCheck enabled. It's not clear exactly how this happened, however, the node that experienced this issue was the first node created in the cluster.

**To Reproduce**

Unknown... create a cluster on AWS using the reference terraform, where presumably a race exists that can cause the SourceDestinationCheck attribute to be missed. It's possible that the InstanceLaunching event wasn't created or was lost on the first node(s) added to the cluster during terraform creation. 

**Expected behavior**

The SourceDestinationCheck attribute should be set to false on all nodes

** Additional Information **
https://github.com/gravitational/gravity/blob/04a1c8a2f047f03a15d962a75eca4d5869e474d8/lib/autoscale/aws/autoscaler.go#L140
https://github.com/gravitational/gravity/blob/04a1c8a2f047f03a15d962a75eca4d5869e474d8/lib/autoscale/aws/events.go#L103

taking a look at this, it looks like in the AWS configuration dependency graph, the lifecycle hooks depend on the ASG name, so it means the ASG gets created first and will exist for some amount of time before terraform is able to apply the lifecycle hooks, which presumably results in the message getting lost in a race condition...

**Comment by r0mant** [comment]
We have added a reconciler for that in 7.0 (https://github.com/gravitational/gravity/pull/2163) and master (https://github.com/gravitational/gravity/pull/2173).
