### ISSUE TITLE
[BUG] Prevent upgrades that skip versions

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#536]
**Describe the bug**
Gravity doesn't seem to currently prevent upgrades that skip too many versions. This should be enforced in the upgrade scripts and/or tele build to prevent the cluster from breaking when using unsupported upgrade paths.

**Comment by a-palchikov** [comment]
As we already have [a basic way](https://github.com/gravitational/gravity/blob/6.1.1/tool/gravity/cli/clusterupdate.go#L355) of enforcing the installed version minimum we could follow the same version skew rules as kubernetes (using the version of k8s bundled by the runtime application).
But after the work on allowing multiple intermediate kubernetes upgrades, it will probably matter less so we could stay with a single version minimum known to support them.

**Comment by knisbet** [comment]
I suspect the really tricky part though, is the intermediate upgrade stages requires tele build flags, so installation restrictions should react to that. IE an upgrade for 5.0 -> 5.5 that doesn't specify 5.2 as an intermediate stage should prevent the upgrade, where as one that does have the intermediate stage to do 5.0 -> 5.2 -> 5.5 should complete the upgrade.

Also, the way the basic check is setup now leads to the variable not keeping up to date. So process wise or test wise, we should likely ensure that the minimum version is set to a version that we actually test upgrades from in robotest.

**Comment by a-palchikov** [comment]
I agree. One way we could expose the minimum version if in the `gravity version` command. There could be some extended view with additional metadata.

**Comment by wadells** [comment]
This work is being tracked in #1064 now.
