### ISSUE TITLE
[BUG] Web Installer isn't working / throws a 400

### ISSUE THREAD

**Issue by benarent** [gravitational/gravity#557]
While working on screenshots for the Web UI installer I found a few issues.

- [ ] If you have 3 servers, the 1st server doesn't / can't be included in the three server cluster
- [ ] Once two machines are added 'verify' / continue either time out or blur out.  ( It shows that it's calling prechecks but (pending) takes a while .

![image](https://user-images.githubusercontent.com/559288/62257604-0bd0cb80-b3bb-11e9-8d45-eafc238f2b11.png)

Example showing Precheck, but taking a while to complete. 
![image](https://user-images.githubusercontent.com/559288/62257863-89490b80-b3bc-11e9-8025-c9b10a34b9db.png)

- [ ] when I came back, I was logged out of the web ui. 
![image](https://user-images.githubusercontent.com/559288/62260062-81419980-b3c5-11e9-8e04-7834a9643114.png)

- [ ] After adding three, and waiting 15+min i got this error.
![image](https://user-images.githubusercontent.com/559288/62262211-b43b5b80-b3cc-11e9-9447-19585d47a4dd.png)

**Comment by alex-kovoy** [comment]
>  If you have 3 servers, the 1st server doesn't / can't be included in the three server cluster

Just to clarify, the 1st server was the one on which the installer had been running. This server will not show up in the list of servers unless you execute the given command.

We should display a modal dialog to prevent a user from wondering around and changing the values while precheck is running.

We also should handle browser refresh (F5), so if precheck is running, the modal appears.

**Comment by alex-kovoy** [comment]
@r0mant what do you think?

**Comment by wadells** [comment]
Should this be split apart in to 2-3 smaller issues? Based on the information provided, I'm not convinced the problems described in https://github.com/gravitational/gravity/issues/557#issue-475418316 are related behavior.  Thoughts @benarent ?

**Comment by benarent** [comment]
@wadells yes, I would agree.  Feel free to split it up.
