### ISSUE TITLE
[BUG] CoreDNS consumes all available CPU when no upstream DNS server is configured 

### ISSUE THREAD

**Issue by terrywang** [gravitational/gravity#613]
**Describe the bug**

CoreDNS (and NetworkManager on host) consume all available CPU time slice when no DNS nameserver is configured for cluster node VMs.

**To Reproduce**

Create a cluster with 1 controller and 1 worker, in my case it's Anypoint Runtime Fabric (`gravity 5.5.12`) cluster with 1 controller and 2 workers, RHEL 7.6 with no DNS (nameserver configured via DHCP or manually).

It's an edge case (in a /24 network where there is no DNS server, all outbound HTTP connections go thru a squid proxy, of course the proxy does name resolution) but it does exist!

**Expected behavior**

CoreDNS should be aware of no upstream DNS server is available and behave normally instead of panicking, causing host NetworkManager to co-panic.

**Logs**

top output after installation (no changes were made)

```bash
top - 17:10:51 up 6 days,  1:32,  1 user,  load average: 4.33, 4.44, 4.49
Tasks: 239 total,   3 running, 236 sleeping,   0 stopped,   0 zombie
%Cpu(s): 21.9 us, 40.6 sy,  0.0 ni, 29.7 id,  0.0 wa,  0.0 hi,  7.8 si,  0.0 st
KiB Mem : 16266732 total, 11258140 free,   576348 used,  4432244 buff/cache
KiB Swap:  7815164 total,  7815164 free,        0 used. 15172244 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20682 planet    20   0  142788  31768  13012 S 231.2  0.2 293:08.02 coredns
 6076 root      20   0  473984  10912   6536 S  37.5  0.1 116:56.76 NetworkManager
20673 root      20   0  137672  24372  11876 S   6.2  0.1   0:10.31 kube-proxy
    1 root      20   0  195116   6892   2820 S   0.0  0.0   0:15.81 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.10 kthreadd
    3 root      20   0       0      0      0 R   0.0  0.0   0:21.23 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
    7 root      rt   0       0      0      0 S   0.0  0.0   0:00.17 migration/0
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh
    9 root      20   0       0      0      0 S   0.0  0.0   0:25.33 rcu_sched
   10 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain
   11 root      rt   0       0      0      0 S   0.0  0.0   0:02.14 watchdog/0
   12 root      rt   0       0      0      0 S   0.0  0.0   0:01.79 watchdog/1
   13 root      rt   0       0      0      0 S   0.0  0.0   0:00.17 migration/1

```

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]: RHEL 7.6
 - Gravity [e.g. 5.5.4]: 5.5.12
 - Platform [e.g. Vmware, AWS]: VMware

**Additional context**

Background: gravity 5.3+ migrated from `kube-dns` to `coredns` (which happened in mainline k8s back in v1.10.0).

Installed 2 clusters using both gravity 5.5.12 and 5.5.15 (runtime-fabric-1.1.1561762676-fed2e0b.tar.gz), same issue happened to both.

The network does not have a DNS name server so all node VMs have an empty `/etc/resolv.conf`.

All outbound traffic goes thru a proxy, which does name resolution (whitelisting only). This worked well until the installation is done and VMware ops team complained about excessive CPU consumption for the VMs.

A quick look into the worker VMs, `coredns` (container) and NetworkManager (on the VM host) were consuming almost all available CPU (4 vCPU) time slice, `loadavg` was over 4 for all 3 categories.

It's an edge case but it does exist. NetworkManager behaviour may just be a symptom (not cause).

Workaround is to make a DNS server available for the cluster node VMs, configure each node VM (`/etc/resolv.conf`), update `coredns` `configmap` to reflect the upstream dns (forward) and then restart the gravity planet master container on each VM to get VMs' load back to normal.

NOTE: simply deleting coredns pod and coredns-worker pods on workers didn't help.

#gravity-mulesoft
https://grv8.slack.com/archives/GK01B18DT/p1566357901087400

**Comment by knisbet** [comment]
I suspect this is caused by the following planet code:
https://github.com/gravitational/planet/blob/master/lib/utils/dns.go#L36
https://github.com/gravitational/planet/blob/master/lib/utils/dns.go#L178-L180

When reading the resolv.conf, it appears that when reading a resolv.conf with no upstream servers, we populate a default upstream nameserver of 127.0.0.1, and then this get's copied to the coredns configuration as an upstream nameserver. I'm not sure why this triggers high cpu usage within coredns, but the upstream of 127.0.0.1 shouldn't be set as an upstream server in the coredns configuration.

**Comment by a-palchikov** [comment]
I've reproduced this and took a CPU profile which revealed that coredns is spinning on the path where it communicates with the proxy (`127.0.0.1` here). I don't think it is a valid expectation that it hardspins even if health check interval is `0` but I think it hits a pathological code path in backoff where in this case, the exponential backoff is no longer exponential and always yields `0` as the next backoff step.
I'm not sure why we reset the health check default from 0.5s to 0. I can see why an explicit interval might help in case coredns changes the default, but given the backoff package behavior, I'd set it to a positive value instead - e.g. if a shorter interval is desired, to something like `0.1s`
