### ISSUE TITLE
[BUG] systemd fails to remove unit and enters a broken 'not-found' state

### ISSUE THREAD

**Issue by eldios** [gravitational/gravity#614]
**Describe the bug**

After having a fully or partially installed cluster, if systemd fails while running `leave` (even on one node clusters) the gravity-planet systemd unit will change its state to `not-found` and just be unmanageable from then on.

The only way to clean the broken Systemd unit is to run `reset-failed` and/or reboot the server. 

**To Reproduce**

Current environment:

```
ubuntu@node:~$ systemctl --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

ubuntu@node:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

ubuntu@node:~$ uname -a
Linux build-node 4.13.0-1012-gcp #16-Ubuntu SMP Thu Mar 15 12:00:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

install Gravity and then run leave... systemd will turn the gravity-planet unit to `not-found` status and won't be able to reinstall or do other Gravity operations on it.

**Expected behavior**

Gravity should successfully clean or at least report the failed removal of the systemd unit.

**Comment by a-palchikov** [comment]
A unit will only become `not-found` with the unit file removed - guess this is what ends up happening.
