### ISSUE TITLE
Add ability to enable privileged containers

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#619]
### Problem

By default Gravity clusters do not allow users to run privileged containers by starting kube-apiserver with `--allow-privileged=false` flag.

Privileged containers are required though in order to be able to run things like custom CNI plugins and dynamic volume provisioners.

In the ideal use-case, a user would be able to write a proper PSP spec to run these services but it is oftentimes quite challenging (if possible at all) to figure out the required set of capabilities, and plus privileged containers enable some additional features on top of that such as ability to see and manage all host devices which is required for volume plugins.

### Solution

Keep privileged containers off by default but add an ability to enable them by adding the flag to the cluster manifest, extending the existing "systemOptions" section:

```yaml
systemOptions:
  allowPrivileged: true
```

This way the cluster will have an ability to run privileged containers and users will still be able to control this ability in a fine-grained way by using PSPs.

**Comment by kontsevoy** [comment]
Some thoughts:

1. You've used different verbs for the manifest and the CLI: "enable" vs "allow". I would pick "allow". 
2. But do we need a verb at all? What if we trade it for more descriptive name: `--privileged-containers=false` or `privilegedContainers: false`?

@benarent may add some more.

**Comment by r0mant** [comment]
@kontsevoy @benarent The `--allow-privileged` flag is not ours - it's a flag of `kube-apiserver` which is a Kubernetes binary - we're not adding a CLI flag to our binaries, only the manifest field.

We could use `allowPrivileged` instead, yeah, to keep it consistent with the flag name.
