### ISSUE TITLE
Pass configuration arguments to the installer / application.

### ISSUE THREAD

**Issue by benarent** [gravitational/gravity#660]
We should provide an easy way to pass configuration arguments to the installer / application. @klizhentas says we support this under the hood via Helm but it’s not exposed, not documented.

**Comment by klizhentas** [comment]
@benarent this might be an opportunity to build a simple UI/dialog generator based on helm values.yaml.

**Comment by klizhentas** [comment]
so people can have easy ways to supply some configuration parameters when installing apps

**Comment by r0mant** [comment]
As a first step I'm going to add the same `--values` and `--set` flags to `gravity install` and `gravity upgrade` commands (and respective scripts), now that `tele build` supports them too.

This should give users a nice and familiar way to pass their Helm values like they're used to. For example, `gravity app install` command (that installs an app image) already supports them so it will be consistent with everything.

And we can build the UI for it anytime later when we have spare cycles.
