### ISSUE TITLE
Air-gapped installs can sometimes call upstream resolvers. 

### ISSUE THREAD

**Issue by benarent** [gravitational/gravity#695]
When testing air-gapped installs, ran into the problem where upstream resolvers must be reachable. (@knisbet : I’ve had some ideas on this, mainly that we may be able to drop the search paths within the host/pod `resolv.conf`, and use coredns autopath plugin, which might be able to prevent leaking search queries.)

**Comment by wadells** [comment]
I believe https://github.com/gravitational/gravity/issues/380 and https://github.com/gravitational/gravity/issues/257 may be prior art for this.
