### ISSUE TITLE
Let customers turn off install check / skip with actionable errors. 

### ISSUE THREAD

**Issue by benarent** [gravitational/gravity#707]
When checks fail, let them turn off checks that fail / skip checks with actionable errors. Give them an idea as what to do. Detect/fail more gracefully on systems that don't meet I/O requirements, and/or have less stringent I/O requirements

**Comment by r0mant** [comment]
Might have to postpone it until after 7.0. We have a way to skip all the checks via environment variable, maybe we can start with documenting it.

**Comment by wadells** [comment]
The work here should feed into (or utilize) the work in https://github.com/gravitational/gravity/issues/663

**Comment by aelkugia** [comment]
As @r0mant mentioned we currently have an env variable related to skipping all preflight checks (`GRAVITY_CHECKS_OFF`), but this does not allow for specific checks to be excluded. 

Some customers who are running into some false positives yield to just turning off all checks. Other feedback has been related to interest in skipping OS checks. There was previously a discussion related to this in the following [doc](https://docs.google.com/document/d/1dFeMxjrjW_i--1dVH4l6ID3vi4Pp6jDi0Ju7ECJTDL0/edit#heading=h.7mje6cnfmjl).

**Comment by aelkugia** [comment]
Closing via #1847
