### ISSUE TITLE
Support kernel >=5.1

### ISSUE THREAD

**Issue by zimmski** [gravitational/gravity#735]
**Describe the bug**

Some kernel modules that do not exist with kernel >=5.1 anymore, e.g. https://cateee.net/lkddb/web-lkddb/NF_NAT_IPV4.html, are required by the gravity preflight checks. Hence, Gravity cannot be installed e.g. on openSUSE's MicroOS.

**To Reproduce**
Install a VM e.g. with the latest openSUSE MicroOS which is using kernel 5.2 (at the moment) and try to install gravity.

**Expected behavior**
The expectation is that Gravity is supported on every modern distribution. Hence, also on distributions with a newer kernel.

**Logs**
```
...
[×] required kernel boot config parameter CONFIG_NF_NAT_IPV4 missing
[×] required kernel boot config parameter CONFIG_NF_NAT_NEEDED missing
```

**Environment (please complete the following information):**
 - OS openSUSE MicroOS
 - Gravity 6.2.0

**Comment by klizhentas** [comment]
@knisbet @r0mant can you please take a look? seems important

**Comment by knisbet** [comment]
@zimmski Thank you for the report, we'll take a look at ensuring these checks only run on the relevant kernels.

As a workaround, you can use `GRAVITY_CHECKS_OFF=true` as an environment variable to the install and join commands, that will skip any pre-flight check failures.

**Comment by zimmski** [comment]
Thanks for the changes. We try to run Gravity on openSUSE MicroOS and #745 is basically the next issue we ran into.

**Comment by zimmski** [comment]
Sorry for closing the issue, I just saw that the change is still not upstreamed.
