### ISSUE TITLE
Support Read-Only root-filesystem

### ISSUE THREAD

**Issue by JukicD** [gravitational/gravity#745]
**Describe the bug**

The installation fails in a read-only root-filesystem as used in openSuse MicroOS. 
Error Message is:
> [ERROR]: failed to install gravity binary in any of [/usr/bin/gravity /writable/bin/gravity], failed to install binary

**To Reproduce**

Install openSuse MicroOS. 
https://en.opensuse.org/Kubic:MicroOS

Take care of pre-flight checkis if the kernel is >=5.1 as described [here](https://github.com/gravitational/gravity/issues/735)

Try to install gravity from snapshot-tarball
> ./gravity install --cloud-provider=generic --token=secret

**Expected behavior**

It would be nice if we could pass the directory in which it should be installed via env-vars.
i.e.
> ./gravity install --cloud-provider=generic --token=secret --writable-dir=/home/gravity/bin

The system on which it is installed should take care that the given path is in $PATH.

**Logs**

 - OS: openSuse MicroOS
 - Gravity: 6.2
 - Platform: Virtualbox, KVM

**Additional context**

We have evaluated gravity as a perfect fit for what we need in delivering our application to customers on a k8s cluster. These clusters will run on VMs in a low maintenance environment. Therefore we have chosen openSuses MicroOS for its transactional-update features for which it needs a read-only root-filesystem.

Related code: 
[Default](https://github.com/gravitational/gravity/blob/30a6d78121b7df8d709402cff5b7f2f7ca9b6f7e/lib/defaults/defaults.go#L290)

[Where the error is thrown](https://github.com/gravitational/gravity/blob/945b1338eb561f0fc48e92096c673819b8ee6743/lib/install/utils.go#L300)

Thanks

**Comment by knisbet** [comment]
Hi @JukicD thanks for the report. 

As we don't currently support openSuse MicroOS it's hard to commit to compatibility. The list of distributions we support and explicitly test against are available here: https://gravitational.com/gravity/docs/requirements/

This might be a good issue for the community to work on, where ideally we would natively support the distribution without additional install flags.
