### ISSUE TITLE
Improve gravity status command after network partition

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/gravity#750]
While testing gravity behavior after a network partition, I noticed that the `status` command has a delay of ~15 minutes. 

From my understanding, the issue seems to be that once a network partition is created, it takes a while for kubernetes to realize that a node is unreachable. During that time, if status is requested, the gravity `statusOperator` will attempt to send an HTTP request to the node that kubernetes has not yet realized is unreachable. The `statusOperator` has no timeout value for an HTTP request and ends up waiting until kubernetes has discovered the network partition.

Here is a relevant article better explaining the scenario: https://medium.com/expedia-group-tech/improving-kubernetes-responsiveness-under-network-partitioning-df00403a6d97

It is not ideal to have users waiting ~15 minutes for a response from a gravity command even if the kubernetes cluster itself is not yet in a functional state.

We can improve the user experience by adding a timeout when initializing the `statusOperator` so that users aren't left hanging and wondering what is wrong. With this change, after timing out, `gravity status` should respond with a status that lets the user know that the cluster is currently 'offline'?

**Comment by a-palchikov** [comment]
That's a very good point - I see no reason why we'd create an HTTP client to a service without a timeout by default.
