### ISSUE TITLE
user(name="2408e2f8-5b1a-4903-9c05-0a218ddc76e0.determinedgates439") not found

### ISSUE THREAD

**Issue by benarent** [gravitational/gravity#757]
**Describe the bug**
While creating a new cluster, I started by trying to log into my cluster.  When creating users, I ran into `user(name="2408e2f8-5b1a-4903-9c05-0a218ddc76e0.determinedgates439") not found` 

![image](https://user-images.githubusercontent.com/559288/66171468-257dd180-e5fd-11e9-9f37-fa435d746dbc.png)
![image](https://user-images.githubusercontent.com/559288/66171475-2c0c4900-e5fd-11e9-8137-c8c1381068dd.png)
![image](https://user-images.githubusercontent.com/559288/66171503-4514fa00-e5fd-11e9-962f-b7a0a5d427a6.png)

**To Reproduce**

**Expected behavior**

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: 6
 - Platform [e.g. Vmware, AWS]: DigitalOcean 

**Additional context**

**Comment by benarent** [comment]
FYI Team, debugged this IRL with @r0mant .

**Comment by r0mant** [comment]
Fixed in [6.1.7](https://gravitational.com/gravity/docs/changelog/#617-october-11th-2019) and [6.2.1](https://gravitational.com/gravity/docs/changelog/#621-october-11th-2019).
