### ISSUE TITLE
[Question] Will Gravity upgrade updates the existing cronjobs as well?

### ISSUE THREAD

**Issue by JoeyLuffa** [gravitational/gravity#767]
Let's say, I have  a CronJob running with version V1. When doing a Gravity upgrade using this way: https://github.com/gravitational/workshop/blob/master/gravity101/v2/upgrade.yaml  Will it patch the existing running cronjobs with V2 version? thanks.

**Comment by a-palchikov** [comment]
No, this will not happen automatically but you can create an application upgrade hook to do this manually. See [image manifest](https://gravitational.com/gravity/docs/pack/#image-manifest) for details.

**Comment by knisbet** [comment]
Please note, we have a searchable community forum we're trying to use for community questions and answers: https://community.gravitational.com/c/gravity
