### ISSUE TITLE
`gravity status` timeline view

### ISSUE THREAD

**Issue by klizhentas** [gravitational/gravity#839]
## Gravity Status Timeline

Right now whenever operators encounter the issue with gravity, they use `gravity status` to observe the broken cluster.

UI view is not always available or possible, that's why CLI experience is very important to them.

Gravity status shows only current status what does not allow them to observe changes of statuses over time.

* Satellite should collect snapshots of different `gravity status` versions (stored as a limited sequence of diverging statuses). Old snapshots should expire, however it should be really cheap to store last 256 different statuses over time.

* `gravity status` should show a timeline of changes over time rendering past snapshots in a timeline.

**Comment by r0mant** [comment]
@bernardjkim has begun working on this, currently working on the feature design.

**Comment by bernardjkim** [comment]
[Design Doc](https://docs.google.com/document/d/1CKQn5qcVg3QIGuZ11eAPzdBlS6LU2AK0RJ3Ww3btmN4/edit#)

**Comment by aelkugia** [comment]
Another issue that was reported with `gravity status` was #881, if possible can we take a look at this? It is for a specific scenario where all UDP traffic was blocked from master to worker nodes by a firewall. In this case `gravity status` should detect this and report an error clearly.

**Comment by jeff-1amstudios** [comment]
Whats the latest on this feature? When will we have something that we can start playing with?

**Comment by r0mant** [comment]
@jeff-1amstudios Hi Jeff! @bernardjkim is wrapping it up, with the testing and reviews I think it should make it into a release in a couple of weeks.

**Comment by bernardjkim** [comment]
`gravity status history` command is available on gravity v5.5, v6.1, v6.3. 
Remaining improvements/bugs will be tracked in #1157.
