### ISSUE TITLE
gravity check should verify upgrade related checks

### ISSUE THREAD

**Issue by klizhentas** [gravitational/gravity#840]
## Description

Whenever users would like to make sure that upgrade will succeed, they would like to run `gravity check upgrade` from the install tarball.

This command should run the upgrade to the point of running preflight checks without performing any actions.

This will allow users to very that upgrade in `dry run` mode could succeed.

**Comment by r0mant** [comment]
This is available starting from [5.5.27](https://gravitational.com/gravity/docs/changelog/#5527-november-1st-2019). Will be forward-ported to 6.1/6.2 and master as well.
