### ISSUE TITLE
gravity plan --tail

### ISSUE THREAD

**Issue by klizhentas** [gravitational/gravity#841]
## Description

Ops teams constantly execute `gravity plan` to verify the current stage of the execution.

`gravity plan --follow` or `gravity plan --tail` should show the current operation progress with auto refresh.

**Comment by jeff-1amstudios** [comment]
The usage case behind this is to have the ability to wait for the upgrade to complete, so our customers can just execute a single command. In this mode, `plan` should exit with a non-zero status code if one of the steps fails

**Comment by r0mant** [comment]
Closing as a part of https://github.com/gravitational/gravity/issues/1807.
