### ISSUE TITLE
[BUG] Always set sysctls and modules

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#850]
Similar to https://github.com/gravitational/gravity.e/issues/3897

If a sysctl happens to be set at install time, the autofix code won't  configure the setting at boot. This can be commonly caused by install gravity on a node, uninstalling gravity, than re-installing gravity. On the reinstall the sysctls will have been set by the first install, and as such the sysctl configuration at boot will be missing.

Relevant code: https://github.com/gravitational/gravity/blob/master/lib/checks/autofix/autofix.go#L108-L118

**Comment by a-palchikov** [comment]
I think simplest would be to generate the `sysctl` file and the list of modules to load unconditionally - there will be no need for autofix.

**Comment by knisbet** [comment]
I believe the sysctl side of this was done but not linked to the ticket, however, it wasn't done for kernel modules and OSS users are seeing problems in the install -> uninstall -> install scenario with missed modules.
