### ISSUE TITLE
[BUG] Gravity self signed certificates don't meet requirements MacOS Catalina

### ISSUE THREAD

**Issue by knisbet** [gravitational/gravity#868]
Gravity: 6.1.11
Browser: Opera or Chrome on MacOS Catalina

![image](https://user-images.githubusercontent.com/12373072/68320312-bbd66480-008d-11ea-8b9d-943090eda5af.png)

On MacOS this is generating error about the certificate being revoked in several browsers. Doing some very quick research, this appears to be due to requirements changes on self signed certs in MacOS catalina.

https://superuser.com/questions/1492207/neterr-cert-revoked-in-chrome-chromium-introduced-with-macos-catalina

Macos cataline has some new requirements:
https://support.apple.com/en-us/HT210176

## Implementation details

Self-signed cert is generated in https://github.com/gravitational/gravity/blob/version/7.0.x/lib/process/process.go#L2320.

**Comment by helgi** [comment]
I get this on Mojave with the latest Chrome where I have to do a one-off approval for the 127.0.0.1 redirect on logins; very recent. Related?

**Comment by austintp** [comment]
Looks like this issue has been prioritized. Is it slated for any particular release yet? Thanks!
