### ISSUE TITLE
[Enhancement] `gravity status` failed to detect blocked UDP traffic

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#881]
**What happened:**

Customer reported applications which make requests to kubernetes services fail to deploy with:

`i/o timeout connecting to "10.100.x.x"`

`gravity status` reported cluster is `active and healthy`

Root cause was all UDP traffic was blocked from master to worker nodes by firewall. 

**What should happen:**

`gravity status` health check should detect this situation of blocked UDP traffic and report error clearly

[Design Doc](https://docs.google.com/document/d/1zJGGYLPWmNioanIpzuvtjZNffgFzJ-Ezkv3vP3kLKLM/edit#)

**Comment by bernardjkim** [comment]
Closed in #1301 (5.5), #1306 (6.1), #1309 (6.3) and #1310 (7.0).
Closed in https://github.com/gravitational/gravity/pull/1293 (5.5), https://github.com/gravitational/gravity/pull/1321 (6.1), and https://github.com/gravitational/gravity/pull/1324 (6.3).
