### ISSUE TITLE
Upgrade to Helm 3

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#890]
Helm 3 is out: https://helm.sh/blog/helm-3-released/.

We should see what it'd take to upgrade to it, in particular:

* Revendor Helm 3 and update our integration with it in regards to Application Catalog functionality.
* Get rid of `tiller-app`, just ship the new `helm` binary in planet.

Once we're upgraded, we should work on iteratively migrating all our system apps to use Helm instead of plain K8s specs.

**Comment by helgi** [comment]
One thing to note here is the chart apiVersion aspect, which makes charts working on v2 not work on v3. Even latest 2.x exhibit that.

way to test it is grab a chart and run `helm lint` against it, ideally in strict mode

**Comment by dirien** [comment]
Hi, some thumbs up from the Schwarz Group. Looking forward to get Helm 3 support. 💯

**Comment by dorsany** [comment]
maybe as an intermediate step, you can add additional flag like `--helm3` to the `gravity app install`?
In that way you still support `helm2` as a default, and provide the ability to use `helm3` and to skip the local tiller

> Helm v2 and v3 can quite happily manage the same cluster. The Helm versions can be installed on the same or separate systems

from: https://helm.sh/docs/topics/v2_v3_migration/

**Comment by yonatankahana** [comment]
any updates about that? helm 2 is end-of-life and some charts are becoming not available to use in gravity, for example, it is enough that chart will use `deepCopy` in the template to be incompatible with gravity.
