### ISSUE TITLE
pre-checks on Helm look for outdated plugin

### ISSUE THREAD

**Issue by kujenga** [gravitational/gravity#92]
The check that `helm` is properly installed [1] requires that a template plugin is installed which is now part of helm core. Echoing what's in the README of the plugin repo: https://github.com/technosophos/helm-template/blob/master/README.md, `helm template` has been built-in to Helm in recent versions, so explicitly checking for the plugin is not needed, you could instead just check for the presence of the `helm template` sub-command.

> If you are using a recent version of Helm, you do not need this anymore!
> 
> helm template is now a built-in part of Helm. Just run helm template --help with your existing Helm.

[1] https://github.com/gravitational/gravity/blob/6f649396628d626845f98c966f505fc7bfd9bb58/lib/utils/helm.go#L34-L42

**Comment by a-palchikov** [comment]
Thanks for pointing this out. We're using helm `v2.5.1` so this still applies but will definitely change the implementation once we upgrade our version of helm.

**Comment by r0mant** [comment]
The latest versions of gravity (5.5.0-alpha.xxx) do not require helm at all anymore.
