### ISSUE TITLE
Updating service CIDR broken on multinode cluster

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#936]
**Versions**:
- **Gravity** (use `gravity version`): 5.5.28 (6.x, master)
- **Planet** (use `planet version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**What happened**:
When updating the service CIDR with a `ClusterConfiguration` resource, the first node cannot stays degraded after the restart as the agent fails to create the DNS service (and environment file) due to changes in the `kubernetes` service IP which creates a failure chain for other services.

Following changes should be considered:
  * recreating **all** services as api server is unable to do this automatically and will log the following:
```
E1120 15:20:36.666240   13103 repair.go:171] the cluster IP 10.100.254.233 for service bandwagon/kube-system is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.666274   13103 repair.go:171] the cluster IP 10.100.20.164 for service gravity-site/kube-system is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.667414   13103 repair.go:171] the cluster IP 10.100.33.34 for service kube-dns/kube-system is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.668512   13103 repair.go:171] the cluster IP 10.100.208.169 for service kube-dns-worker/kube-system is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.669597   13103 repair.go:171] the cluster IP 10.100.17.195 for service log-collector/kube-system is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.670761   13103 repair.go:171] the cluster IP 10.100.247.96 for service lr-aggregator/kube-system is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.671802   13103 repair.go:171] the cluster IP 10.100.140.255 for service alertmanager-main/monitoring is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.672957   13103 repair.go:171] the cluster IP 10.100.162.150 for service grafana/monitoring is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.674062   13103 repair.go:171] the cluster IP 10.100.61.67 for service prometheus-adapter/monitoring is not within the service CIDR 10.200.0.0/24; please recreate
E1120 15:20:36.675208   13103 repair.go:171] the cluster IP 10.100.249.17 for service prometheus-k8s/monitoring is not within the service CIDR 10.200.0.0/24; please recreate
```
  * generating new secrets to include the new service IP for the api server:
```
Get https://<new-service-ip>/api/v1/componentstatuses/scheduler: x509: certificate is valid for 127.0.0.1, 127.0.0.2, 10.128.0.4, 10.100.0.1, not <new-service-ip>
```
```
I1120 15:23:46.701649   13103 log.go:172] http: TLS handshake error from 10.128.0.72:48854: remote error: tls: bad certificate
```

**Comment by a-palchikov** [comment]
Additionally, the planet's setup should be carefully considered w.r.t to updates to service CIDR as it uses the cluster IPs of the `kube-dns` /  `kube-dns-worker` services as DNS configuration.
Also, pod CIDR changes are likely to cause issues with `flannel`.
All in all, this requires careful consideration and testing which was not done when the resource has been initially conceived and implemented.
