### ISSUE TITLE
tele build should not package dependencies that are disabled

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#937]
It's possible to disable certain system applications from being installed in the cluster in the image manifest, for example monitoring components, logging components, tiller (in older versions), OpenEBS, etc.

When disabled, respective applications will not be installed in the cluster, but their packages will still be included in the cluster image tarball during tele build.

We should update tele build to not package unnecessary dependencies. For example, OpenEBS alone (via storage-app) adds about 900MB of dead weight (if it's not enabled).

**Comment by helgi** [comment]
Isn't this a duplication of https://github.com/gravitational/gravity/issues/887 ? :D

**Comment by r0mant** [comment]
Yes it is :)
