### ISSUE TITLE
[Enhancement] Invoke test alert for SMTP + improvements to SMTP configuration

### ISSUE THREAD

**Issue by aelkugia** [gravitational/gravity#938]
**Test alert for SMTP:**

There should be a way to test whether SMTP alerting is working properly. Some functionality to invoke a test alert to see if SMTP is indeed set up correctly. Currently, customers are configuring SMTP, but are not entirely certain if the set up has been correct. 

**SMTP configuration improvements:**

Separately, customers find it hard to configure SMTP alerting if their SMTP server isn’t set up to use authentication, because the configuration asks for a username and password.

@r0mant feel free to add more context to this

**Comment by benarent** [comment]
It might also be useful to just provide an API endpoint via Hosted Email clients ( but in a provider agonistic manor ), and also provide a full suite of user controllable test commands.
