### ISSUE TITLE
Ability to force upgrade regardless of version

### ISSUE THREAD

**Issue by adamlamar** [gravitational/gravity#940]
When gravity detects that a new cluster image is older than the existing cluster image version, it will refuse to upgrade. This seems like the right behavior in general.

In some circumstances, especially when testing or changing artifact names, it is useful to force an upgrade even though gravity may consider it a downgrade based solely on the semantic versioning scheme.

Request: create a `--force` or `--ignore-version-check` option to allow `./upgrade` to proceed anyway.

**Comment by shiranp** [comment]
+1
