### ISSUE TITLE
Lingering serf members cause degraded status

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#943]
If a node has been removed from the cluster as a part of the shrink operation but its planet is still running for whatever reason (which most usually happens when using ASG) the serf agent may remain a part of the serf cluster and will enter "failed" state when the planet finally shuts down.

This means that the removed node is not among Kubernetes or Gravity nodes anymore but planet still thinks it's got a failed member and thus the status will be degraded until the member is manually force-leave'd.

The "gravity status" won't show this "rogue" node b/c as far as Gravity's concerned, it's not a part of the cluster and the status will just say "degraded" without a clue of why. The failed member should be visible in "planet status" but it's not a user-facing command.

We should extend "gravity status" to give better visibility into why a cluster is degraded in such cases.

As an idea, instead of using "cluster state" as a single source of truth for the cluster nodes, we could compare a list of gravity/k8s/etcd/serf nodes and alert to any found discrepancies.

**Comment by helgi** [comment]
This happened again on a 6.2 cluster; @tosih will provide more info.

**Comment by helgi** [comment]
I've seen this happen various times now on 6.2, primarily when nodes are being rolled using AWS ASGs

**Comment by tariq1890** [comment]
Any updates on this issue?

**Comment by r0mant** [comment]
Going to prioritize this higher, customers keep running into this.

**Comment by helgi** [comment]
Did this get backported to 5.5? I saw the serf bump but not the code change
