### ISSUE TITLE
[BUG] gravity plan commands are not aware of enterprise-specific phases

### ISSUE THREAD

**Issue by r0mant** [gravitational/gravity#989]
**Describe the bug**

The relatively new `gravity plan xxx` set of commands live in the open-source repo and thus are not aware of any enterprise-specific install fsm phases.

This causes issues with install. If an installer attempts to execute any of the enterprise-specific phases on a remote node, it uses `gravity plan execute --phase=/license` (for example) command which fails with "unknown phase" error.

Previously, install was using `gravity install --phase=/xxx` command which is aware of enterprise fsm but this has changed somewhere b/w 5.5.24 and 5.5.30.

**To Reproduce**

Build a cluster image that requires a license using enterprise tools. Try to install and invoke `gravity plan execute --phase=/license` command manually. It should fail with "unknown phase" error.

**Expected behavior**

The `gravity plan` commands should be enterprise-aware just like the `gravity install` is.

**Logs**

**Environment (please complete the following information):**
 - OS [e.g. Redhat 7.4]:
 - Gravity [e.g. 5.5.4]: **5.5.30**
 - Platform [e.g. Vmware, AWS]:

**Additional context**

**Comment by wadells** [comment]
Has `gravity plan execute --phase` ever worked correctly with enterprise phases?

Is `gravity install --phase` still available and working properly?

Trying to figure out if this could break scripts out in the wild, or just provide inconsistencies when swapping `plan` for `install`.  As someone learning the product, it seems like this may be an oversight in plan, but not necessarily a regression in something that used to work.
