### ISSUE TITLE
[BUG] instructions provided by WebUI to add a new node are incorrect

### ISSUE THREAD

**Issue by eldios** [gravitational/gravity#996]
**Describe the bug**
When adding a new node via WebUI the instructions are provided are not correct.

If you use STEP 1 as is, you'll have to prepend `./` to STEP 2 (`./gravity [...]`) to have the process work.

But even that won't work, cause the gravity binary will lack the executable permission, quickly fixed by `chmod u+x gravity` though that's not mentioned.

I guess those commands are meant to be used verbatim with no other action from the user, thus they probably need to be fixed.

**To Reproduce**

Try to add a new node via WebUI by going to NODES and press the ADD button at the top right corner of the central section.

**Environment (please complete the following information):**
 - Gravity [e.g. 5.5.4]: verified on Gravity 5.5.x, 6.1.x and 7.0.x

**Comment by alex-kovoy** [comment]
@benarent could you provide an updated set of instructions?
